<Project>
  <ItemGroup Condition="'$(MSBuildProjectName)' == 'Supprocom.MathBlocks'">
    <PackageReference Include="Microsoft.CodeAnalysis.PublicApiAnalyzers" Version="[5.6.0]" PrivateAssets="all" />
    <AdditionalFiles Include="$(MSBuildProjectDirectory)/PublicAPI.Shipped.txt" />
    <AdditionalFiles Include="$(MSBuildProjectDirectory)/PublicAPI.Unshipped.txt" />
  </ItemGroup>
  <ItemGroup Condition="'$(MSBuildProjectName)' == 'Supprocom.MathBlocks.Tests'">
    <PackageReference Include="xunit.analyzers" Version="[2.1.0]" PrivateAssets="all" />
  </ItemGroup>
</Project>
