namespace Supprocom.MathBlocks.Cuda;

internal enum MathBlockCudaFamily
{
    Advanced,
    Complex,
    Geometry,
    Graph,
    Matrix,
    Probability,
    Scalar,
    SequencePath,
    Statistics,
    Transport,
    Vector,
}

internal readonly record struct MathBlockCudaFeature(string Identity, MathBlockCudaFamily Family, int Opcode);

internal static class MathBlockCudaFeatureIndex
{
    internal static IReadOnlyCollection<string> SupportedIdentities { get; } =
    [
        BooleanVectorAllV1BlockCuda.Identity,
        BooleanVectorAndV1BlockCuda.Identity,
        BooleanVectorAnyV1BlockCuda.Identity,
        BooleanVectorNotV1BlockCuda.Identity,
        BooleanVectorOrV1BlockCuda.Identity,
        BooleanVectorTrueCountV1BlockCuda.Identity,
        BooleanVectorTrueIndicesV1BlockCuda.Identity,
        BooleanVectorXorV1BlockCuda.Identity,
        BooleanAndV1BlockCuda.Identity,
        BooleanNotV1BlockCuda.Identity,
        BooleanOrV1BlockCuda.Identity,
        BooleanXorV1BlockCuda.Identity,
        CapacityChoquetIntegralV1BlockCuda.Identity,
        CapacityIsSubmodularV1BlockCuda.Identity,
        CapacityMobiusTransformV1BlockCuda.Identity,
        CombinatoricsBallotCountV1BlockCuda.Identity,
        CombinatoricsBinomialCoefficientV1BlockCuda.Identity,
        CombinatoricsFactorialV1BlockCuda.Identity,
        CombinatoricsNonemptySubsetSumsV1BlockCuda.Identity,
        ComplexMatrixPickV1BlockCuda.Identity,
        ComplexVectorCreateV1BlockCuda.Identity,
        ComplexVectorImaginaryV1BlockCuda.Identity,
        ComplexVectorMagnitudeV1BlockCuda.Identity,
        ComplexVectorRealV1BlockCuda.Identity,
        ComplexAddV1BlockCuda.Identity,
        ComplexConjugateV1BlockCuda.Identity,
        ComplexCreateV1BlockCuda.Identity,
        ComplexDivideV1BlockCuda.Identity,
        ComplexExponentialV1BlockCuda.Identity,
        ComplexFromPolarV1BlockCuda.Identity,
        ComplexMagnitudeV1BlockCuda.Identity,
        ComplexMultiplyV1BlockCuda.Identity,
        ComplexNaturalLogarithmV1BlockCuda.Identity,
        ComplexNegateV1BlockCuda.Identity,
        ComplexPhaseV1BlockCuda.Identity,
        ComplexPowerV1BlockCuda.Identity,
        ComplexSquareRootV1BlockCuda.Identity,
        ComplexSubtractV1BlockCuda.Identity,
        CooperativeShapleyValuesV1BlockCuda.Identity,
        ExtensionMcshaneV1BlockCuda.Identity,
        ExtensionWhitneyV1BlockCuda.Identity,
        GeometryBarycentricCoordinatesV1BlockCuda.Identity,
        GeometryCentroidV1BlockCuda.Identity,
        GeometryCircumradiusV1BlockCuda.Identity,
        GeometryContainsPointV1BlockCuda.Identity,
        GeometryConvexHullV1BlockCuda.Identity,
        GeometryDelaunayGraphV1BlockCuda.Identity,
        GeometryDiameterV1BlockCuda.Identity,
        GeometryDiscreteFrechetDistanceV1BlockCuda.Identity,
        GeometryDistanceV1BlockCuda.Identity,
        GeometryFisherRaoDistanceV1BlockCuda.Identity,
        GeometryGabrielGraphV1BlockCuda.Identity,
        GeometryHalfspaceDepthV1BlockCuda.Identity,
        GeometryHausdorffDistanceV1BlockCuda.Identity,
        GeometryPathLengthV1BlockCuda.Identity,
        GeometryPerimeterV1BlockCuda.Identity,
        GeometryPointToSegmentDistanceV1BlockCuda.Identity,
        GeometryPolygonAreaV1BlockCuda.Identity,
        GeometrySignedPolygonAreaV1BlockCuda.Identity,
        GeometrySimplicialDepthV1BlockCuda.Identity,
        GraphAlgebraicConnectivityV1BlockCuda.Identity,
        GraphConductanceV1BlockCuda.Identity,
        GraphConnectedComponentCountV1BlockCuda.Identity,
        GraphDegreeV1BlockCuda.Identity,
        GraphFromDirectedAdjacencyV1BlockCuda.Identity,
        GraphHodgePotentialV1BlockCuda.Identity,
        GraphHodgeResidualNormV1BlockCuda.Identity,
        GraphIsConnectedV1BlockCuda.Identity,
        GraphMinimumSpanningForestV1BlockCuda.Identity,
        GraphPageRankV1BlockCuda.Identity,
        GraphToDirectedAdjacencyV1BlockCuda.Identity,
        GraphTriangleCountV1BlockCuda.Identity,
        GraphUndirectedAdjacencyMatrixV1BlockCuda.Identity,
        GraphUndirectedLaplacianV1BlockCuda.Identity,
        GraphUndirectedShortestPathsV1BlockCuda.Identity,
        GraphWeightedDegreeV1BlockCuda.Identity,
        InequalityGiniCoefficientV1BlockCuda.Identity,
        InequalityLorenzCurveV1BlockCuda.Identity,
        InformationBhattacharyyaCoefficientV1BlockCuda.Identity,
        InformationBinaryShannonEntropyV1BlockCuda.Identity,
        InformationConditionalMutualInformationV1BlockCuda.Identity,
        InformationCrossEntropyV1BlockCuda.Identity,
        InformationGiniImpurityV1BlockCuda.Identity,
        InformationHellingerDistanceV1BlockCuda.Identity,
        InformationJensenShannonV1BlockCuda.Identity,
        InformationKullbackLeiblerV1BlockCuda.Identity,
        InformationMutualInformationV1BlockCuda.Identity,
        InformationRenyiEntropyV1BlockCuda.Identity,
        InformationShannonEntropyV1BlockCuda.Identity,
        InformationTotalVariationDistanceV1BlockCuda.Identity,
        InformationTsallisEntropyV1BlockCuda.Identity,
        MarkovEntropyProductionV1BlockCuda.Identity,
        MarkovStationaryDistributionV1BlockCuda.Identity,
        MatrixAddV1BlockCuda.Identity,
        MatrixAppendRowV1BlockCuda.Identity,
        MatrixColumnSumsV1BlockCuda.Identity,
        MatrixColumnV1BlockCuda.Identity,
        MatrixCommutatorV1BlockCuda.Identity,
        MatrixDeterminantV1BlockCuda.Identity,
        MatrixDiagonalFromVectorV1BlockCuda.Identity,
        MatrixDiagonalV1BlockCuda.Identity,
        MatrixExponentialV1BlockCuda.Identity,
        MatrixFlattenV1BlockCuda.Identity,
        MatrixFrobeniusNormV1BlockCuda.Identity,
        MatrixGramV1BlockCuda.Identity,
        MatrixHadamardProductV1BlockCuda.Identity,
        MatrixHankelV1BlockCuda.Identity,
        MatrixIdentityV1BlockCuda.Identity,
        MatrixIntegerPowerV1BlockCuda.Identity,
        MatrixInverseV1BlockCuda.Identity,
        MatrixIsPositiveDefiniteV1BlockCuda.Identity,
        MatrixIsSymmetricV1BlockCuda.Identity,
        MatrixIsTotallyNonnegativeV1BlockCuda.Identity,
        MatrixKroneckerProductV1BlockCuda.Identity,
        MatrixLargestSymmetricEigenvalueV1BlockCuda.Identity,
        MatrixMaximalMinorsV1BlockCuda.Identity,
        MatrixMultiplyVectorV1BlockCuda.Identity,
        MatrixMultiplyV1BlockCuda.Identity,
        MatrixOuterProductV1BlockCuda.Identity,
        MatrixPerronValueV1BlockCuda.Identity,
        MatrixPerronVectorV1BlockCuda.Identity,
        MatrixPrincipalMinorsV1BlockCuda.Identity,
        MatrixRankV1BlockCuda.Identity,
        MatrixReshapeV1BlockCuda.Identity,
        MatrixRowSumsV1BlockCuda.Identity,
        MatrixRowV1BlockCuda.Identity,
        MatrixScaleV1BlockCuda.Identity,
        MatrixSchurComplementV1BlockCuda.Identity,
        MatrixSmallestSymmetricEigenvalueV1BlockCuda.Identity,
        MatrixSolveV1BlockCuda.Identity,
        MatrixSpectralNormV1BlockCuda.Identity,
        MatrixStackRowsV1BlockCuda.Identity,
        MatrixSubtractV1BlockCuda.Identity,
        MatrixSymmetricEigenvaluesV1BlockCuda.Identity,
        MatrixToeplitzV1BlockCuda.Identity,
        MatrixTraceV1BlockCuda.Identity,
        MatrixTransposeV1BlockCuda.Identity,
        OrderIsotonicRegressionV1BlockCuda.Identity,
        OrderMajorizesV1BlockCuda.Identity,
        PathCumulativeDeviationV1BlockCuda.Identity,
        PathDynamicTimeWarpingV1BlockCuda.Identity,
        PathFirstPassageIndexV1BlockCuda.Identity,
        PathHysteresisV1BlockCuda.Identity,
        PathLeadLagTransformV1BlockCuda.Identity,
        PathLongestTrueRunV1BlockCuda.Identity,
        PathMaximumDeclineV1BlockCuda.Identity,
        PathMaximumRelativeDeclineV1BlockCuda.Identity,
        PathPowerVariationV1BlockCuda.Identity,
        PathQuadraticVariationV1BlockCuda.Identity,
        PathRecurrenceRateV1BlockCuda.Identity,
        PathReflectedCumulativeSumV1BlockCuda.Identity,
        PathRunLengthEncodeV1BlockCuda.Identity,
        PathSignatureLevelOneV1BlockCuda.Identity,
        PathSignatureLevelThreeV1BlockCuda.Identity,
        PathSignatureLevelTwoV1BlockCuda.Identity,
        PathTotalVariationV1BlockCuda.Identity,
        PathTurningPointCountV1BlockCuda.Identity,
        PathZeroCrossingCountV1BlockCuda.Identity,
        PointSetFromMatrixV1BlockCuda.Identity,
        PointSetToMatrixV1BlockCuda.Identity,
        PolynomialBernsteinEvaluateV1BlockCuda.Identity,
        PolynomialCubicRootsV1BlockCuda.Identity,
        PolynomialDerivativeV1BlockCuda.Identity,
        PolynomialElementarySymmetricV1BlockCuda.Identity,
        PolynomialEvaluateV1BlockCuda.Identity,
        ProbabilityLogSumExpV1BlockCuda.Identity,
        ProbabilityNormalCdfV1BlockCuda.Identity,
        ProbabilityNormalizeV1BlockCuda.Identity,
        ProbabilityPoissonCdfV1BlockCuda.Identity,
        ProbabilityPoissonPmfV1BlockCuda.Identity,
        ProbabilitySoftmaxV1BlockCuda.Identity,
        ProjectiveHilbertDistanceV1BlockCuda.Identity,
        ScalarAbsoluteV1BlockCuda.Identity,
        ScalarAddV1BlockCuda.Identity,
        ScalarArcCosineV1BlockCuda.Identity,
        ScalarArcSineV1BlockCuda.Identity,
        ScalarArcTangent2V1BlockCuda.Identity,
        ScalarArcTangentV1BlockCuda.Identity,
        ScalarBinaryLogarithmV1BlockCuda.Identity,
        ScalarCeilingV1BlockCuda.Identity,
        ScalarClampV1BlockCuda.Identity,
        ScalarCommonLogarithmV1BlockCuda.Identity,
        ScalarCosineV1BlockCuda.Identity,
        ScalarCubeRootV1BlockCuda.Identity,
        ScalarCubeV1BlockCuda.Identity,
        ScalarDivideV1BlockCuda.Identity,
        ScalarEqualV1BlockCuda.Identity,
        ScalarExponentialV1BlockCuda.Identity,
        ScalarFloorV1BlockCuda.Identity,
        ScalarGreaterOrEqualV1BlockCuda.Identity,
        ScalarGreaterThanV1BlockCuda.Identity,
        ScalarHyperbolicCosineV1BlockCuda.Identity,
        ScalarHyperbolicSineV1BlockCuda.Identity,
        ScalarHyperbolicTangentV1BlockCuda.Identity,
        ScalarInverseHyperbolicCosineV1BlockCuda.Identity,
        ScalarInverseHyperbolicSineV1BlockCuda.Identity,
        ScalarInverseHyperbolicTangentV1BlockCuda.Identity,
        ScalarLessOrEqualV1BlockCuda.Identity,
        ScalarLessThanV1BlockCuda.Identity,
        ScalarLogOnePlusV1BlockCuda.Identity,
        ScalarLogisticV1BlockCuda.Identity,
        ScalarLogitV1BlockCuda.Identity,
        ScalarMaximumV1BlockCuda.Identity,
        ScalarMinimumV1BlockCuda.Identity,
        ScalarModuloV1BlockCuda.Identity,
        ScalarMultiplyV1BlockCuda.Identity,
        ScalarNaturalLogarithmV1BlockCuda.Identity,
        ScalarNegateV1BlockCuda.Identity,
        ScalarNotEqualV1BlockCuda.Identity,
        ScalarPositivePartV1BlockCuda.Identity,
        ScalarPowerV1BlockCuda.Identity,
        ScalarReciprocalV1BlockCuda.Identity,
        ScalarRoundV1BlockCuda.Identity,
        ScalarSelectV1BlockCuda.Identity,
        ScalarSignV1BlockCuda.Identity,
        ScalarSineV1BlockCuda.Identity,
        ScalarSoftplusV1BlockCuda.Identity,
        ScalarSquareRootV1BlockCuda.Identity,
        ScalarSquareV1BlockCuda.Identity,
        ScalarSubtractV1BlockCuda.Identity,
        ScalarTangentV1BlockCuda.Identity,
        ScalarTruncateV1BlockCuda.Identity,
        SequenceConvolutionV1BlockCuda.Identity,
        SequenceDifferenceV1BlockCuda.Identity,
        SequenceExponentialMovingAverageV1BlockCuda.Identity,
        SequenceRollingMaximumV1BlockCuda.Identity,
        SequenceRollingMeanV1BlockCuda.Identity,
        SequenceRollingMedianV1BlockCuda.Identity,
        SequenceRollingMinimumV1BlockCuda.Identity,
        SequenceRollingQuantileV1BlockCuda.Identity,
        SequenceRollingStandardDeviationV1BlockCuda.Identity,
        SequenceRollingSumV1BlockCuda.Identity,
        SequenceRollingVarianceV1BlockCuda.Identity,
        ShapeGreatestConvexMinorantV1BlockCuda.Identity,
        ShapeIsCompletelyMonotoneV1BlockCuda.Identity,
        ShapeIsLogConcaveV1BlockCuda.Identity,
        ShapeLeastConcaveMajorantV1BlockCuda.Identity,
        SpecialBetaV1BlockCuda.Identity,
        SpecialErrorFunctionV1BlockCuda.Identity,
        SpecialLogGammaV1BlockCuda.Identity,
        SpecialRegularizedIncompleteBetaV1BlockCuda.Identity,
        StateTransitionCountsV1BlockCuda.Identity,
        StatisticsAutocorrelationV1BlockCuda.Identity,
        StatisticsCentralMomentV1BlockCuda.Identity,
        StatisticsCovarianceMatrixV1BlockCuda.Identity,
        StatisticsDistanceCorrelationV1BlockCuda.Identity,
        StatisticsHistogramV1BlockCuda.Identity,
        StatisticsInterquartileRangeV1BlockCuda.Identity,
        StatisticsKendallTauBV1BlockCuda.Identity,
        StatisticsLinearInterceptV1BlockCuda.Identity,
        StatisticsLinearRSquaredV1BlockCuda.Identity,
        StatisticsLinearSlopeV1BlockCuda.Identity,
        StatisticsMedianAbsoluteDeviationV1BlockCuda.Identity,
        StatisticsPearsonCorrelationV1BlockCuda.Identity,
        StatisticsPopulationCovarianceV1BlockCuda.Identity,
        StatisticsPopulationExcessKurtosisV1BlockCuda.Identity,
        StatisticsPopulationSkewnessV1BlockCuda.Identity,
        StatisticsPopulationStandardDeviationV1BlockCuda.Identity,
        StatisticsPopulationVarianceV1BlockCuda.Identity,
        StatisticsPseudomedianV1BlockCuda.Identity,
        StatisticsRawMomentV1BlockCuda.Identity,
        StatisticsRootMeanSquareV1BlockCuda.Identity,
        StatisticsSampleCovarianceV1BlockCuda.Identity,
        StatisticsSampleStandardDeviationV1BlockCuda.Identity,
        StatisticsSampleVarianceV1BlockCuda.Identity,
        StatisticsSpearmanCorrelationV1BlockCuda.Identity,
        StatisticsTheilSenSlopeV1BlockCuda.Identity,
        StatisticsWeightedMeanV1BlockCuda.Identity,
        StatisticsWeightedPopulationVarianceV1BlockCuda.Identity,
        SurvivalDiscreteHazardV1BlockCuda.Identity,
        SurvivalProductLimitV1BlockCuda.Identity,
        TopologyZeroDimensionalPersistenceV1BlockCuda.Identity,
        TransformDiscreteFourierV1BlockCuda.Identity,
        TransformHaarV1BlockCuda.Identity,
        TransformInverseDiscreteFourierV1BlockCuda.Identity,
        TransformWalshHadamardV1BlockCuda.Identity,
        TransportAssignmentCostV1BlockCuda.Identity,
        TransportCouplingCostV1BlockCuda.Identity,
        TransportEnergyDistanceV1BlockCuda.Identity,
        TransportMinimumAssignmentV1BlockCuda.Identity,
        TransportMonotoneCouplingV1BlockCuda.Identity,
        TransportOrderedEarthMoverV1BlockCuda.Identity,
        TransportSinkhornCouplingV1BlockCuda.Identity,
        TransportUniformWassersteinV1BlockCuda.Identity,
        TransportWeightedWasserstein1V1BlockCuda.Identity,
        TropicalMaxPlusMultiplyV1BlockCuda.Identity,
        TropicalMinPlusMultiplyV1BlockCuda.Identity,
        VectorAbsoluteV1BlockCuda.Identity,
        VectorAddScalarV1BlockCuda.Identity,
        VectorAddV1BlockCuda.Identity,
        VectorAppendV1BlockCuda.Identity,
        VectorArgMaximumV1BlockCuda.Identity,
        VectorArgMinimumV1BlockCuda.Identity,
        VectorConcatenateV1BlockCuda.Identity,
        VectorCumulativeProductV1BlockCuda.Identity,
        VectorCumulativeSumV1BlockCuda.Identity,
        VectorDivideV1BlockCuda.Identity,
        VectorDotV1BlockCuda.Identity,
        VectorEqualV1BlockCuda.Identity,
        VectorExponentialV1BlockCuda.Identity,
        VectorGatherV1BlockCuda.Identity,
        VectorGeometricMeanV1BlockCuda.Identity,
        VectorGreaterThanV1BlockCuda.Identity,
        VectorIndexV1BlockCuda.Identity,
        VectorL1NormV1BlockCuda.Identity,
        VectorL2NormV1BlockCuda.Identity,
        VectorLengthV1BlockCuda.Identity,
        VectorLessThanV1BlockCuda.Identity,
        VectorLinspaceV1BlockCuda.Identity,
        VectorMaximumV1BlockCuda.Identity,
        VectorMeanV1BlockCuda.Identity,
        VectorMedianV1BlockCuda.Identity,
        VectorMinimumV1BlockCuda.Identity,
        VectorMultiplyV1BlockCuda.Identity,
        VectorNaturalLogarithmV1BlockCuda.Identity,
        VectorNormalizeL1V1BlockCuda.Identity,
        VectorNormalizeL2V1BlockCuda.Identity,
        VectorPairV1BlockCuda.Identity,
        VectorPositivePartV1BlockCuda.Identity,
        VectorPowerV1BlockCuda.Identity,
        VectorPrependV1BlockCuda.Identity,
        VectorProductV1BlockCuda.Identity,
        VectorQuantileV1BlockCuda.Identity,
        VectorRankV1BlockCuda.Identity,
        VectorRepeatV1BlockCuda.Identity,
        VectorReverseV1BlockCuda.Identity,
        VectorScaleV1BlockCuda.Identity,
        VectorSelectV1BlockCuda.Identity,
        VectorSignV1BlockCuda.Identity,
        VectorSliceV1BlockCuda.Identity,
        VectorSortV1BlockCuda.Identity,
        VectorSquareRootV1BlockCuda.Identity,
        VectorSquareV1BlockCuda.Identity,
        VectorStandardizeV1BlockCuda.Identity,
        VectorSubtractV1BlockCuda.Identity,
        VectorSumV1BlockCuda.Identity,
        VectorUniqueV1BlockCuda.Identity,
    ];

    internal static MathBlockCudaFeature Resolve(string identity) => identity switch
    {
        BooleanVectorAllV1BlockCuda.Identity => BooleanVectorAllV1BlockCuda.Feature,
        BooleanVectorAndV1BlockCuda.Identity => BooleanVectorAndV1BlockCuda.Feature,
        BooleanVectorAnyV1BlockCuda.Identity => BooleanVectorAnyV1BlockCuda.Feature,
        BooleanVectorNotV1BlockCuda.Identity => BooleanVectorNotV1BlockCuda.Feature,
        BooleanVectorOrV1BlockCuda.Identity => BooleanVectorOrV1BlockCuda.Feature,
        BooleanVectorTrueCountV1BlockCuda.Identity => BooleanVectorTrueCountV1BlockCuda.Feature,
        BooleanVectorTrueIndicesV1BlockCuda.Identity => BooleanVectorTrueIndicesV1BlockCuda.Feature,
        BooleanVectorXorV1BlockCuda.Identity => BooleanVectorXorV1BlockCuda.Feature,
        BooleanAndV1BlockCuda.Identity => BooleanAndV1BlockCuda.Feature,
        BooleanNotV1BlockCuda.Identity => BooleanNotV1BlockCuda.Feature,
        BooleanOrV1BlockCuda.Identity => BooleanOrV1BlockCuda.Feature,
        BooleanXorV1BlockCuda.Identity => BooleanXorV1BlockCuda.Feature,
        CapacityChoquetIntegralV1BlockCuda.Identity => CapacityChoquetIntegralV1BlockCuda.Feature,
        CapacityIsSubmodularV1BlockCuda.Identity => CapacityIsSubmodularV1BlockCuda.Feature,
        CapacityMobiusTransformV1BlockCuda.Identity => CapacityMobiusTransformV1BlockCuda.Feature,
        CombinatoricsBallotCountV1BlockCuda.Identity => CombinatoricsBallotCountV1BlockCuda.Feature,
        CombinatoricsBinomialCoefficientV1BlockCuda.Identity => CombinatoricsBinomialCoefficientV1BlockCuda.Feature,
        CombinatoricsFactorialV1BlockCuda.Identity => CombinatoricsFactorialV1BlockCuda.Feature,
        CombinatoricsNonemptySubsetSumsV1BlockCuda.Identity => CombinatoricsNonemptySubsetSumsV1BlockCuda.Feature,
        ComplexMatrixPickV1BlockCuda.Identity => ComplexMatrixPickV1BlockCuda.Feature,
        ComplexVectorCreateV1BlockCuda.Identity => ComplexVectorCreateV1BlockCuda.Feature,
        ComplexVectorImaginaryV1BlockCuda.Identity => ComplexVectorImaginaryV1BlockCuda.Feature,
        ComplexVectorMagnitudeV1BlockCuda.Identity => ComplexVectorMagnitudeV1BlockCuda.Feature,
        ComplexVectorRealV1BlockCuda.Identity => ComplexVectorRealV1BlockCuda.Feature,
        ComplexAddV1BlockCuda.Identity => ComplexAddV1BlockCuda.Feature,
        ComplexConjugateV1BlockCuda.Identity => ComplexConjugateV1BlockCuda.Feature,
        ComplexCreateV1BlockCuda.Identity => ComplexCreateV1BlockCuda.Feature,
        ComplexDivideV1BlockCuda.Identity => ComplexDivideV1BlockCuda.Feature,
        ComplexExponentialV1BlockCuda.Identity => ComplexExponentialV1BlockCuda.Feature,
        ComplexFromPolarV1BlockCuda.Identity => ComplexFromPolarV1BlockCuda.Feature,
        ComplexMagnitudeV1BlockCuda.Identity => ComplexMagnitudeV1BlockCuda.Feature,
        ComplexMultiplyV1BlockCuda.Identity => ComplexMultiplyV1BlockCuda.Feature,
        ComplexNaturalLogarithmV1BlockCuda.Identity => ComplexNaturalLogarithmV1BlockCuda.Feature,
        ComplexNegateV1BlockCuda.Identity => ComplexNegateV1BlockCuda.Feature,
        ComplexPhaseV1BlockCuda.Identity => ComplexPhaseV1BlockCuda.Feature,
        ComplexPowerV1BlockCuda.Identity => ComplexPowerV1BlockCuda.Feature,
        ComplexSquareRootV1BlockCuda.Identity => ComplexSquareRootV1BlockCuda.Feature,
        ComplexSubtractV1BlockCuda.Identity => ComplexSubtractV1BlockCuda.Feature,
        CooperativeShapleyValuesV1BlockCuda.Identity => CooperativeShapleyValuesV1BlockCuda.Feature,
        ExtensionMcshaneV1BlockCuda.Identity => ExtensionMcshaneV1BlockCuda.Feature,
        ExtensionWhitneyV1BlockCuda.Identity => ExtensionWhitneyV1BlockCuda.Feature,
        GeometryBarycentricCoordinatesV1BlockCuda.Identity => GeometryBarycentricCoordinatesV1BlockCuda.Feature,
        GeometryCentroidV1BlockCuda.Identity => GeometryCentroidV1BlockCuda.Feature,
        GeometryCircumradiusV1BlockCuda.Identity => GeometryCircumradiusV1BlockCuda.Feature,
        GeometryContainsPointV1BlockCuda.Identity => GeometryContainsPointV1BlockCuda.Feature,
        GeometryConvexHullV1BlockCuda.Identity => GeometryConvexHullV1BlockCuda.Feature,
        GeometryDelaunayGraphV1BlockCuda.Identity => GeometryDelaunayGraphV1BlockCuda.Feature,
        GeometryDiameterV1BlockCuda.Identity => GeometryDiameterV1BlockCuda.Feature,
        GeometryDiscreteFrechetDistanceV1BlockCuda.Identity => GeometryDiscreteFrechetDistanceV1BlockCuda.Feature,
        GeometryDistanceV1BlockCuda.Identity => GeometryDistanceV1BlockCuda.Feature,
        GeometryFisherRaoDistanceV1BlockCuda.Identity => GeometryFisherRaoDistanceV1BlockCuda.Feature,
        GeometryGabrielGraphV1BlockCuda.Identity => GeometryGabrielGraphV1BlockCuda.Feature,
        GeometryHalfspaceDepthV1BlockCuda.Identity => GeometryHalfspaceDepthV1BlockCuda.Feature,
        GeometryHausdorffDistanceV1BlockCuda.Identity => GeometryHausdorffDistanceV1BlockCuda.Feature,
        GeometryPathLengthV1BlockCuda.Identity => GeometryPathLengthV1BlockCuda.Feature,
        GeometryPerimeterV1BlockCuda.Identity => GeometryPerimeterV1BlockCuda.Feature,
        GeometryPointToSegmentDistanceV1BlockCuda.Identity => GeometryPointToSegmentDistanceV1BlockCuda.Feature,
        GeometryPolygonAreaV1BlockCuda.Identity => GeometryPolygonAreaV1BlockCuda.Feature,
        GeometrySignedPolygonAreaV1BlockCuda.Identity => GeometrySignedPolygonAreaV1BlockCuda.Feature,
        GeometrySimplicialDepthV1BlockCuda.Identity => GeometrySimplicialDepthV1BlockCuda.Feature,
        GraphAlgebraicConnectivityV1BlockCuda.Identity => GraphAlgebraicConnectivityV1BlockCuda.Feature,
        GraphConductanceV1BlockCuda.Identity => GraphConductanceV1BlockCuda.Feature,
        GraphConnectedComponentCountV1BlockCuda.Identity => GraphConnectedComponentCountV1BlockCuda.Feature,
        GraphDegreeV1BlockCuda.Identity => GraphDegreeV1BlockCuda.Feature,
        GraphFromDirectedAdjacencyV1BlockCuda.Identity => GraphFromDirectedAdjacencyV1BlockCuda.Feature,
        GraphHodgePotentialV1BlockCuda.Identity => GraphHodgePotentialV1BlockCuda.Feature,
        GraphHodgeResidualNormV1BlockCuda.Identity => GraphHodgeResidualNormV1BlockCuda.Feature,
        GraphIsConnectedV1BlockCuda.Identity => GraphIsConnectedV1BlockCuda.Feature,
        GraphMinimumSpanningForestV1BlockCuda.Identity => GraphMinimumSpanningForestV1BlockCuda.Feature,
        GraphPageRankV1BlockCuda.Identity => GraphPageRankV1BlockCuda.Feature,
        GraphToDirectedAdjacencyV1BlockCuda.Identity => GraphToDirectedAdjacencyV1BlockCuda.Feature,
        GraphTriangleCountV1BlockCuda.Identity => GraphTriangleCountV1BlockCuda.Feature,
        GraphUndirectedAdjacencyMatrixV1BlockCuda.Identity => GraphUndirectedAdjacencyMatrixV1BlockCuda.Feature,
        GraphUndirectedLaplacianV1BlockCuda.Identity => GraphUndirectedLaplacianV1BlockCuda.Feature,
        GraphUndirectedShortestPathsV1BlockCuda.Identity => GraphUndirectedShortestPathsV1BlockCuda.Feature,
        GraphWeightedDegreeV1BlockCuda.Identity => GraphWeightedDegreeV1BlockCuda.Feature,
        InequalityGiniCoefficientV1BlockCuda.Identity => InequalityGiniCoefficientV1BlockCuda.Feature,
        InequalityLorenzCurveV1BlockCuda.Identity => InequalityLorenzCurveV1BlockCuda.Feature,
        InformationBhattacharyyaCoefficientV1BlockCuda.Identity => InformationBhattacharyyaCoefficientV1BlockCuda.Feature,
        InformationBinaryShannonEntropyV1BlockCuda.Identity => InformationBinaryShannonEntropyV1BlockCuda.Feature,
        InformationConditionalMutualInformationV1BlockCuda.Identity => InformationConditionalMutualInformationV1BlockCuda.Feature,
        InformationCrossEntropyV1BlockCuda.Identity => InformationCrossEntropyV1BlockCuda.Feature,
        InformationGiniImpurityV1BlockCuda.Identity => InformationGiniImpurityV1BlockCuda.Feature,
        InformationHellingerDistanceV1BlockCuda.Identity => InformationHellingerDistanceV1BlockCuda.Feature,
        InformationJensenShannonV1BlockCuda.Identity => InformationJensenShannonV1BlockCuda.Feature,
        InformationKullbackLeiblerV1BlockCuda.Identity => InformationKullbackLeiblerV1BlockCuda.Feature,
        InformationMutualInformationV1BlockCuda.Identity => InformationMutualInformationV1BlockCuda.Feature,
        InformationRenyiEntropyV1BlockCuda.Identity => InformationRenyiEntropyV1BlockCuda.Feature,
        InformationShannonEntropyV1BlockCuda.Identity => InformationShannonEntropyV1BlockCuda.Feature,
        InformationTotalVariationDistanceV1BlockCuda.Identity => InformationTotalVariationDistanceV1BlockCuda.Feature,
        InformationTsallisEntropyV1BlockCuda.Identity => InformationTsallisEntropyV1BlockCuda.Feature,
        MarkovEntropyProductionV1BlockCuda.Identity => MarkovEntropyProductionV1BlockCuda.Feature,
        MarkovStationaryDistributionV1BlockCuda.Identity => MarkovStationaryDistributionV1BlockCuda.Feature,
        MatrixAddV1BlockCuda.Identity => MatrixAddV1BlockCuda.Feature,
        MatrixAppendRowV1BlockCuda.Identity => MatrixAppendRowV1BlockCuda.Feature,
        MatrixColumnSumsV1BlockCuda.Identity => MatrixColumnSumsV1BlockCuda.Feature,
        MatrixColumnV1BlockCuda.Identity => MatrixColumnV1BlockCuda.Feature,
        MatrixCommutatorV1BlockCuda.Identity => MatrixCommutatorV1BlockCuda.Feature,
        MatrixDeterminantV1BlockCuda.Identity => MatrixDeterminantV1BlockCuda.Feature,
        MatrixDiagonalFromVectorV1BlockCuda.Identity => MatrixDiagonalFromVectorV1BlockCuda.Feature,
        MatrixDiagonalV1BlockCuda.Identity => MatrixDiagonalV1BlockCuda.Feature,
        MatrixExponentialV1BlockCuda.Identity => MatrixExponentialV1BlockCuda.Feature,
        MatrixFlattenV1BlockCuda.Identity => MatrixFlattenV1BlockCuda.Feature,
        MatrixFrobeniusNormV1BlockCuda.Identity => MatrixFrobeniusNormV1BlockCuda.Feature,
        MatrixGramV1BlockCuda.Identity => MatrixGramV1BlockCuda.Feature,
        MatrixHadamardProductV1BlockCuda.Identity => MatrixHadamardProductV1BlockCuda.Feature,
        MatrixHankelV1BlockCuda.Identity => MatrixHankelV1BlockCuda.Feature,
        MatrixIdentityV1BlockCuda.Identity => MatrixIdentityV1BlockCuda.Feature,
        MatrixIntegerPowerV1BlockCuda.Identity => MatrixIntegerPowerV1BlockCuda.Feature,
        MatrixInverseV1BlockCuda.Identity => MatrixInverseV1BlockCuda.Feature,
        MatrixIsPositiveDefiniteV1BlockCuda.Identity => MatrixIsPositiveDefiniteV1BlockCuda.Feature,
        MatrixIsSymmetricV1BlockCuda.Identity => MatrixIsSymmetricV1BlockCuda.Feature,
        MatrixIsTotallyNonnegativeV1BlockCuda.Identity => MatrixIsTotallyNonnegativeV1BlockCuda.Feature,
        MatrixKroneckerProductV1BlockCuda.Identity => MatrixKroneckerProductV1BlockCuda.Feature,
        MatrixLargestSymmetricEigenvalueV1BlockCuda.Identity => MatrixLargestSymmetricEigenvalueV1BlockCuda.Feature,
        MatrixMaximalMinorsV1BlockCuda.Identity => MatrixMaximalMinorsV1BlockCuda.Feature,
        MatrixMultiplyVectorV1BlockCuda.Identity => MatrixMultiplyVectorV1BlockCuda.Feature,
        MatrixMultiplyV1BlockCuda.Identity => MatrixMultiplyV1BlockCuda.Feature,
        MatrixOuterProductV1BlockCuda.Identity => MatrixOuterProductV1BlockCuda.Feature,
        MatrixPerronValueV1BlockCuda.Identity => MatrixPerronValueV1BlockCuda.Feature,
        MatrixPerronVectorV1BlockCuda.Identity => MatrixPerronVectorV1BlockCuda.Feature,
        MatrixPrincipalMinorsV1BlockCuda.Identity => MatrixPrincipalMinorsV1BlockCuda.Feature,
        MatrixRankV1BlockCuda.Identity => MatrixRankV1BlockCuda.Feature,
        MatrixReshapeV1BlockCuda.Identity => MatrixReshapeV1BlockCuda.Feature,
        MatrixRowSumsV1BlockCuda.Identity => MatrixRowSumsV1BlockCuda.Feature,
        MatrixRowV1BlockCuda.Identity => MatrixRowV1BlockCuda.Feature,
        MatrixScaleV1BlockCuda.Identity => MatrixScaleV1BlockCuda.Feature,
        MatrixSchurComplementV1BlockCuda.Identity => MatrixSchurComplementV1BlockCuda.Feature,
        MatrixSmallestSymmetricEigenvalueV1BlockCuda.Identity => MatrixSmallestSymmetricEigenvalueV1BlockCuda.Feature,
        MatrixSolveV1BlockCuda.Identity => MatrixSolveV1BlockCuda.Feature,
        MatrixSpectralNormV1BlockCuda.Identity => MatrixSpectralNormV1BlockCuda.Feature,
        MatrixStackRowsV1BlockCuda.Identity => MatrixStackRowsV1BlockCuda.Feature,
        MatrixSubtractV1BlockCuda.Identity => MatrixSubtractV1BlockCuda.Feature,
        MatrixSymmetricEigenvaluesV1BlockCuda.Identity => MatrixSymmetricEigenvaluesV1BlockCuda.Feature,
        MatrixToeplitzV1BlockCuda.Identity => MatrixToeplitzV1BlockCuda.Feature,
        MatrixTraceV1BlockCuda.Identity => MatrixTraceV1BlockCuda.Feature,
        MatrixTransposeV1BlockCuda.Identity => MatrixTransposeV1BlockCuda.Feature,
        OrderIsotonicRegressionV1BlockCuda.Identity => OrderIsotonicRegressionV1BlockCuda.Feature,
        OrderMajorizesV1BlockCuda.Identity => OrderMajorizesV1BlockCuda.Feature,
        PathCumulativeDeviationV1BlockCuda.Identity => PathCumulativeDeviationV1BlockCuda.Feature,
        PathDynamicTimeWarpingV1BlockCuda.Identity => PathDynamicTimeWarpingV1BlockCuda.Feature,
        PathFirstPassageIndexV1BlockCuda.Identity => PathFirstPassageIndexV1BlockCuda.Feature,
        PathHysteresisV1BlockCuda.Identity => PathHysteresisV1BlockCuda.Feature,
        PathLeadLagTransformV1BlockCuda.Identity => PathLeadLagTransformV1BlockCuda.Feature,
        PathLongestTrueRunV1BlockCuda.Identity => PathLongestTrueRunV1BlockCuda.Feature,
        PathMaximumDeclineV1BlockCuda.Identity => PathMaximumDeclineV1BlockCuda.Feature,
        PathMaximumRelativeDeclineV1BlockCuda.Identity => PathMaximumRelativeDeclineV1BlockCuda.Feature,
        PathPowerVariationV1BlockCuda.Identity => PathPowerVariationV1BlockCuda.Feature,
        PathQuadraticVariationV1BlockCuda.Identity => PathQuadraticVariationV1BlockCuda.Feature,
        PathRecurrenceRateV1BlockCuda.Identity => PathRecurrenceRateV1BlockCuda.Feature,
        PathReflectedCumulativeSumV1BlockCuda.Identity => PathReflectedCumulativeSumV1BlockCuda.Feature,
        PathRunLengthEncodeV1BlockCuda.Identity => PathRunLengthEncodeV1BlockCuda.Feature,
        PathSignatureLevelOneV1BlockCuda.Identity => PathSignatureLevelOneV1BlockCuda.Feature,
        PathSignatureLevelThreeV1BlockCuda.Identity => PathSignatureLevelThreeV1BlockCuda.Feature,
        PathSignatureLevelTwoV1BlockCuda.Identity => PathSignatureLevelTwoV1BlockCuda.Feature,
        PathTotalVariationV1BlockCuda.Identity => PathTotalVariationV1BlockCuda.Feature,
        PathTurningPointCountV1BlockCuda.Identity => PathTurningPointCountV1BlockCuda.Feature,
        PathZeroCrossingCountV1BlockCuda.Identity => PathZeroCrossingCountV1BlockCuda.Feature,
        PointSetFromMatrixV1BlockCuda.Identity => PointSetFromMatrixV1BlockCuda.Feature,
        PointSetToMatrixV1BlockCuda.Identity => PointSetToMatrixV1BlockCuda.Feature,
        PolynomialBernsteinEvaluateV1BlockCuda.Identity => PolynomialBernsteinEvaluateV1BlockCuda.Feature,
        PolynomialCubicRootsV1BlockCuda.Identity => PolynomialCubicRootsV1BlockCuda.Feature,
        PolynomialDerivativeV1BlockCuda.Identity => PolynomialDerivativeV1BlockCuda.Feature,
        PolynomialElementarySymmetricV1BlockCuda.Identity => PolynomialElementarySymmetricV1BlockCuda.Feature,
        PolynomialEvaluateV1BlockCuda.Identity => PolynomialEvaluateV1BlockCuda.Feature,
        ProbabilityLogSumExpV1BlockCuda.Identity => ProbabilityLogSumExpV1BlockCuda.Feature,
        ProbabilityNormalCdfV1BlockCuda.Identity => ProbabilityNormalCdfV1BlockCuda.Feature,
        ProbabilityNormalizeV1BlockCuda.Identity => ProbabilityNormalizeV1BlockCuda.Feature,
        ProbabilityPoissonCdfV1BlockCuda.Identity => ProbabilityPoissonCdfV1BlockCuda.Feature,
        ProbabilityPoissonPmfV1BlockCuda.Identity => ProbabilityPoissonPmfV1BlockCuda.Feature,
        ProbabilitySoftmaxV1BlockCuda.Identity => ProbabilitySoftmaxV1BlockCuda.Feature,
        ProjectiveHilbertDistanceV1BlockCuda.Identity => ProjectiveHilbertDistanceV1BlockCuda.Feature,
        ScalarAbsoluteV1BlockCuda.Identity => ScalarAbsoluteV1BlockCuda.Feature,
        ScalarAddV1BlockCuda.Identity => ScalarAddV1BlockCuda.Feature,
        ScalarArcCosineV1BlockCuda.Identity => ScalarArcCosineV1BlockCuda.Feature,
        ScalarArcSineV1BlockCuda.Identity => ScalarArcSineV1BlockCuda.Feature,
        ScalarArcTangent2V1BlockCuda.Identity => ScalarArcTangent2V1BlockCuda.Feature,
        ScalarArcTangentV1BlockCuda.Identity => ScalarArcTangentV1BlockCuda.Feature,
        ScalarBinaryLogarithmV1BlockCuda.Identity => ScalarBinaryLogarithmV1BlockCuda.Feature,
        ScalarCeilingV1BlockCuda.Identity => ScalarCeilingV1BlockCuda.Feature,
        ScalarClampV1BlockCuda.Identity => ScalarClampV1BlockCuda.Feature,
        ScalarCommonLogarithmV1BlockCuda.Identity => ScalarCommonLogarithmV1BlockCuda.Feature,
        ScalarCosineV1BlockCuda.Identity => ScalarCosineV1BlockCuda.Feature,
        ScalarCubeRootV1BlockCuda.Identity => ScalarCubeRootV1BlockCuda.Feature,
        ScalarCubeV1BlockCuda.Identity => ScalarCubeV1BlockCuda.Feature,
        ScalarDivideV1BlockCuda.Identity => ScalarDivideV1BlockCuda.Feature,
        ScalarEqualV1BlockCuda.Identity => ScalarEqualV1BlockCuda.Feature,
        ScalarExponentialV1BlockCuda.Identity => ScalarExponentialV1BlockCuda.Feature,
        ScalarFloorV1BlockCuda.Identity => ScalarFloorV1BlockCuda.Feature,
        ScalarGreaterOrEqualV1BlockCuda.Identity => ScalarGreaterOrEqualV1BlockCuda.Feature,
        ScalarGreaterThanV1BlockCuda.Identity => ScalarGreaterThanV1BlockCuda.Feature,
        ScalarHyperbolicCosineV1BlockCuda.Identity => ScalarHyperbolicCosineV1BlockCuda.Feature,
        ScalarHyperbolicSineV1BlockCuda.Identity => ScalarHyperbolicSineV1BlockCuda.Feature,
        ScalarHyperbolicTangentV1BlockCuda.Identity => ScalarHyperbolicTangentV1BlockCuda.Feature,
        ScalarInverseHyperbolicCosineV1BlockCuda.Identity => ScalarInverseHyperbolicCosineV1BlockCuda.Feature,
        ScalarInverseHyperbolicSineV1BlockCuda.Identity => ScalarInverseHyperbolicSineV1BlockCuda.Feature,
        ScalarInverseHyperbolicTangentV1BlockCuda.Identity => ScalarInverseHyperbolicTangentV1BlockCuda.Feature,
        ScalarLessOrEqualV1BlockCuda.Identity => ScalarLessOrEqualV1BlockCuda.Feature,
        ScalarLessThanV1BlockCuda.Identity => ScalarLessThanV1BlockCuda.Feature,
        ScalarLogOnePlusV1BlockCuda.Identity => ScalarLogOnePlusV1BlockCuda.Feature,
        ScalarLogisticV1BlockCuda.Identity => ScalarLogisticV1BlockCuda.Feature,
        ScalarLogitV1BlockCuda.Identity => ScalarLogitV1BlockCuda.Feature,
        ScalarMaximumV1BlockCuda.Identity => ScalarMaximumV1BlockCuda.Feature,
        ScalarMinimumV1BlockCuda.Identity => ScalarMinimumV1BlockCuda.Feature,
        ScalarModuloV1BlockCuda.Identity => ScalarModuloV1BlockCuda.Feature,
        ScalarMultiplyV1BlockCuda.Identity => ScalarMultiplyV1BlockCuda.Feature,
        ScalarNaturalLogarithmV1BlockCuda.Identity => ScalarNaturalLogarithmV1BlockCuda.Feature,
        ScalarNegateV1BlockCuda.Identity => ScalarNegateV1BlockCuda.Feature,
        ScalarNotEqualV1BlockCuda.Identity => ScalarNotEqualV1BlockCuda.Feature,
        ScalarPositivePartV1BlockCuda.Identity => ScalarPositivePartV1BlockCuda.Feature,
        ScalarPowerV1BlockCuda.Identity => ScalarPowerV1BlockCuda.Feature,
        ScalarReciprocalV1BlockCuda.Identity => ScalarReciprocalV1BlockCuda.Feature,
        ScalarRoundV1BlockCuda.Identity => ScalarRoundV1BlockCuda.Feature,
        ScalarSelectV1BlockCuda.Identity => ScalarSelectV1BlockCuda.Feature,
        ScalarSignV1BlockCuda.Identity => ScalarSignV1BlockCuda.Feature,
        ScalarSineV1BlockCuda.Identity => ScalarSineV1BlockCuda.Feature,
        ScalarSoftplusV1BlockCuda.Identity => ScalarSoftplusV1BlockCuda.Feature,
        ScalarSquareRootV1BlockCuda.Identity => ScalarSquareRootV1BlockCuda.Feature,
        ScalarSquareV1BlockCuda.Identity => ScalarSquareV1BlockCuda.Feature,
        ScalarSubtractV1BlockCuda.Identity => ScalarSubtractV1BlockCuda.Feature,
        ScalarTangentV1BlockCuda.Identity => ScalarTangentV1BlockCuda.Feature,
        ScalarTruncateV1BlockCuda.Identity => ScalarTruncateV1BlockCuda.Feature,
        SequenceConvolutionV1BlockCuda.Identity => SequenceConvolutionV1BlockCuda.Feature,
        SequenceDifferenceV1BlockCuda.Identity => SequenceDifferenceV1BlockCuda.Feature,
        SequenceExponentialMovingAverageV1BlockCuda.Identity => SequenceExponentialMovingAverageV1BlockCuda.Feature,
        SequenceRollingMaximumV1BlockCuda.Identity => SequenceRollingMaximumV1BlockCuda.Feature,
        SequenceRollingMeanV1BlockCuda.Identity => SequenceRollingMeanV1BlockCuda.Feature,
        SequenceRollingMedianV1BlockCuda.Identity => SequenceRollingMedianV1BlockCuda.Feature,
        SequenceRollingMinimumV1BlockCuda.Identity => SequenceRollingMinimumV1BlockCuda.Feature,
        SequenceRollingQuantileV1BlockCuda.Identity => SequenceRollingQuantileV1BlockCuda.Feature,
        SequenceRollingStandardDeviationV1BlockCuda.Identity => SequenceRollingStandardDeviationV1BlockCuda.Feature,
        SequenceRollingSumV1BlockCuda.Identity => SequenceRollingSumV1BlockCuda.Feature,
        SequenceRollingVarianceV1BlockCuda.Identity => SequenceRollingVarianceV1BlockCuda.Feature,
        ShapeGreatestConvexMinorantV1BlockCuda.Identity => ShapeGreatestConvexMinorantV1BlockCuda.Feature,
        ShapeIsCompletelyMonotoneV1BlockCuda.Identity => ShapeIsCompletelyMonotoneV1BlockCuda.Feature,
        ShapeIsLogConcaveV1BlockCuda.Identity => ShapeIsLogConcaveV1BlockCuda.Feature,
        ShapeLeastConcaveMajorantV1BlockCuda.Identity => ShapeLeastConcaveMajorantV1BlockCuda.Feature,
        SpecialBetaV1BlockCuda.Identity => SpecialBetaV1BlockCuda.Feature,
        SpecialErrorFunctionV1BlockCuda.Identity => SpecialErrorFunctionV1BlockCuda.Feature,
        SpecialLogGammaV1BlockCuda.Identity => SpecialLogGammaV1BlockCuda.Feature,
        SpecialRegularizedIncompleteBetaV1BlockCuda.Identity => SpecialRegularizedIncompleteBetaV1BlockCuda.Feature,
        StateTransitionCountsV1BlockCuda.Identity => StateTransitionCountsV1BlockCuda.Feature,
        StatisticsAutocorrelationV1BlockCuda.Identity => StatisticsAutocorrelationV1BlockCuda.Feature,
        StatisticsCentralMomentV1BlockCuda.Identity => StatisticsCentralMomentV1BlockCuda.Feature,
        StatisticsCovarianceMatrixV1BlockCuda.Identity => StatisticsCovarianceMatrixV1BlockCuda.Feature,
        StatisticsDistanceCorrelationV1BlockCuda.Identity => StatisticsDistanceCorrelationV1BlockCuda.Feature,
        StatisticsHistogramV1BlockCuda.Identity => StatisticsHistogramV1BlockCuda.Feature,
        StatisticsInterquartileRangeV1BlockCuda.Identity => StatisticsInterquartileRangeV1BlockCuda.Feature,
        StatisticsKendallTauBV1BlockCuda.Identity => StatisticsKendallTauBV1BlockCuda.Feature,
        StatisticsLinearInterceptV1BlockCuda.Identity => StatisticsLinearInterceptV1BlockCuda.Feature,
        StatisticsLinearRSquaredV1BlockCuda.Identity => StatisticsLinearRSquaredV1BlockCuda.Feature,
        StatisticsLinearSlopeV1BlockCuda.Identity => StatisticsLinearSlopeV1BlockCuda.Feature,
        StatisticsMedianAbsoluteDeviationV1BlockCuda.Identity => StatisticsMedianAbsoluteDeviationV1BlockCuda.Feature,
        StatisticsPearsonCorrelationV1BlockCuda.Identity => StatisticsPearsonCorrelationV1BlockCuda.Feature,
        StatisticsPopulationCovarianceV1BlockCuda.Identity => StatisticsPopulationCovarianceV1BlockCuda.Feature,
        StatisticsPopulationExcessKurtosisV1BlockCuda.Identity => StatisticsPopulationExcessKurtosisV1BlockCuda.Feature,
        StatisticsPopulationSkewnessV1BlockCuda.Identity => StatisticsPopulationSkewnessV1BlockCuda.Feature,
        StatisticsPopulationStandardDeviationV1BlockCuda.Identity => StatisticsPopulationStandardDeviationV1BlockCuda.Feature,
        StatisticsPopulationVarianceV1BlockCuda.Identity => StatisticsPopulationVarianceV1BlockCuda.Feature,
        StatisticsPseudomedianV1BlockCuda.Identity => StatisticsPseudomedianV1BlockCuda.Feature,
        StatisticsRawMomentV1BlockCuda.Identity => StatisticsRawMomentV1BlockCuda.Feature,
        StatisticsRootMeanSquareV1BlockCuda.Identity => StatisticsRootMeanSquareV1BlockCuda.Feature,
        StatisticsSampleCovarianceV1BlockCuda.Identity => StatisticsSampleCovarianceV1BlockCuda.Feature,
        StatisticsSampleStandardDeviationV1BlockCuda.Identity => StatisticsSampleStandardDeviationV1BlockCuda.Feature,
        StatisticsSampleVarianceV1BlockCuda.Identity => StatisticsSampleVarianceV1BlockCuda.Feature,
        StatisticsSpearmanCorrelationV1BlockCuda.Identity => StatisticsSpearmanCorrelationV1BlockCuda.Feature,
        StatisticsTheilSenSlopeV1BlockCuda.Identity => StatisticsTheilSenSlopeV1BlockCuda.Feature,
        StatisticsWeightedMeanV1BlockCuda.Identity => StatisticsWeightedMeanV1BlockCuda.Feature,
        StatisticsWeightedPopulationVarianceV1BlockCuda.Identity => StatisticsWeightedPopulationVarianceV1BlockCuda.Feature,
        SurvivalDiscreteHazardV1BlockCuda.Identity => SurvivalDiscreteHazardV1BlockCuda.Feature,
        SurvivalProductLimitV1BlockCuda.Identity => SurvivalProductLimitV1BlockCuda.Feature,
        TopologyZeroDimensionalPersistenceV1BlockCuda.Identity => TopologyZeroDimensionalPersistenceV1BlockCuda.Feature,
        TransformDiscreteFourierV1BlockCuda.Identity => TransformDiscreteFourierV1BlockCuda.Feature,
        TransformHaarV1BlockCuda.Identity => TransformHaarV1BlockCuda.Feature,
        TransformInverseDiscreteFourierV1BlockCuda.Identity => TransformInverseDiscreteFourierV1BlockCuda.Feature,
        TransformWalshHadamardV1BlockCuda.Identity => TransformWalshHadamardV1BlockCuda.Feature,
        TransportAssignmentCostV1BlockCuda.Identity => TransportAssignmentCostV1BlockCuda.Feature,
        TransportCouplingCostV1BlockCuda.Identity => TransportCouplingCostV1BlockCuda.Feature,
        TransportEnergyDistanceV1BlockCuda.Identity => TransportEnergyDistanceV1BlockCuda.Feature,
        TransportMinimumAssignmentV1BlockCuda.Identity => TransportMinimumAssignmentV1BlockCuda.Feature,
        TransportMonotoneCouplingV1BlockCuda.Identity => TransportMonotoneCouplingV1BlockCuda.Feature,
        TransportOrderedEarthMoverV1BlockCuda.Identity => TransportOrderedEarthMoverV1BlockCuda.Feature,
        TransportSinkhornCouplingV1BlockCuda.Identity => TransportSinkhornCouplingV1BlockCuda.Feature,
        TransportUniformWassersteinV1BlockCuda.Identity => TransportUniformWassersteinV1BlockCuda.Feature,
        TransportWeightedWasserstein1V1BlockCuda.Identity => TransportWeightedWasserstein1V1BlockCuda.Feature,
        TropicalMaxPlusMultiplyV1BlockCuda.Identity => TropicalMaxPlusMultiplyV1BlockCuda.Feature,
        TropicalMinPlusMultiplyV1BlockCuda.Identity => TropicalMinPlusMultiplyV1BlockCuda.Feature,
        VectorAbsoluteV1BlockCuda.Identity => VectorAbsoluteV1BlockCuda.Feature,
        VectorAddScalarV1BlockCuda.Identity => VectorAddScalarV1BlockCuda.Feature,
        VectorAddV1BlockCuda.Identity => VectorAddV1BlockCuda.Feature,
        VectorAppendV1BlockCuda.Identity => VectorAppendV1BlockCuda.Feature,
        VectorArgMaximumV1BlockCuda.Identity => VectorArgMaximumV1BlockCuda.Feature,
        VectorArgMinimumV1BlockCuda.Identity => VectorArgMinimumV1BlockCuda.Feature,
        VectorConcatenateV1BlockCuda.Identity => VectorConcatenateV1BlockCuda.Feature,
        VectorCumulativeProductV1BlockCuda.Identity => VectorCumulativeProductV1BlockCuda.Feature,
        VectorCumulativeSumV1BlockCuda.Identity => VectorCumulativeSumV1BlockCuda.Feature,
        VectorDivideV1BlockCuda.Identity => VectorDivideV1BlockCuda.Feature,
        VectorDotV1BlockCuda.Identity => VectorDotV1BlockCuda.Feature,
        VectorEqualV1BlockCuda.Identity => VectorEqualV1BlockCuda.Feature,
        VectorExponentialV1BlockCuda.Identity => VectorExponentialV1BlockCuda.Feature,
        VectorGatherV1BlockCuda.Identity => VectorGatherV1BlockCuda.Feature,
        VectorGeometricMeanV1BlockCuda.Identity => VectorGeometricMeanV1BlockCuda.Feature,
        VectorGreaterThanV1BlockCuda.Identity => VectorGreaterThanV1BlockCuda.Feature,
        VectorIndexV1BlockCuda.Identity => VectorIndexV1BlockCuda.Feature,
        VectorL1NormV1BlockCuda.Identity => VectorL1NormV1BlockCuda.Feature,
        VectorL2NormV1BlockCuda.Identity => VectorL2NormV1BlockCuda.Feature,
        VectorLengthV1BlockCuda.Identity => VectorLengthV1BlockCuda.Feature,
        VectorLessThanV1BlockCuda.Identity => VectorLessThanV1BlockCuda.Feature,
        VectorLinspaceV1BlockCuda.Identity => VectorLinspaceV1BlockCuda.Feature,
        VectorMaximumV1BlockCuda.Identity => VectorMaximumV1BlockCuda.Feature,
        VectorMeanV1BlockCuda.Identity => VectorMeanV1BlockCuda.Feature,
        VectorMedianV1BlockCuda.Identity => VectorMedianV1BlockCuda.Feature,
        VectorMinimumV1BlockCuda.Identity => VectorMinimumV1BlockCuda.Feature,
        VectorMultiplyV1BlockCuda.Identity => VectorMultiplyV1BlockCuda.Feature,
        VectorNaturalLogarithmV1BlockCuda.Identity => VectorNaturalLogarithmV1BlockCuda.Feature,
        VectorNormalizeL1V1BlockCuda.Identity => VectorNormalizeL1V1BlockCuda.Feature,
        VectorNormalizeL2V1BlockCuda.Identity => VectorNormalizeL2V1BlockCuda.Feature,
        VectorPairV1BlockCuda.Identity => VectorPairV1BlockCuda.Feature,
        VectorPositivePartV1BlockCuda.Identity => VectorPositivePartV1BlockCuda.Feature,
        VectorPowerV1BlockCuda.Identity => VectorPowerV1BlockCuda.Feature,
        VectorPrependV1BlockCuda.Identity => VectorPrependV1BlockCuda.Feature,
        VectorProductV1BlockCuda.Identity => VectorProductV1BlockCuda.Feature,
        VectorQuantileV1BlockCuda.Identity => VectorQuantileV1BlockCuda.Feature,
        VectorRankV1BlockCuda.Identity => VectorRankV1BlockCuda.Feature,
        VectorRepeatV1BlockCuda.Identity => VectorRepeatV1BlockCuda.Feature,
        VectorReverseV1BlockCuda.Identity => VectorReverseV1BlockCuda.Feature,
        VectorScaleV1BlockCuda.Identity => VectorScaleV1BlockCuda.Feature,
        VectorSelectV1BlockCuda.Identity => VectorSelectV1BlockCuda.Feature,
        VectorSignV1BlockCuda.Identity => VectorSignV1BlockCuda.Feature,
        VectorSliceV1BlockCuda.Identity => VectorSliceV1BlockCuda.Feature,
        VectorSortV1BlockCuda.Identity => VectorSortV1BlockCuda.Feature,
        VectorSquareRootV1BlockCuda.Identity => VectorSquareRootV1BlockCuda.Feature,
        VectorSquareV1BlockCuda.Identity => VectorSquareV1BlockCuda.Feature,
        VectorStandardizeV1BlockCuda.Identity => VectorStandardizeV1BlockCuda.Feature,
        VectorSubtractV1BlockCuda.Identity => VectorSubtractV1BlockCuda.Feature,
        VectorSumV1BlockCuda.Identity => VectorSumV1BlockCuda.Feature,
        VectorUniqueV1BlockCuda.Identity => VectorUniqueV1BlockCuda.Feature,
        _ => throw new NotSupportedException($"MathBlock '{identity}' has no CUDA implementation.")
    };
}
