namespace Supprocom.MathBlocks.Gpu;

internal enum MathBlockGpuFamily
{
    Advanced,
    Complex,
    Geometry,
    Graph,
    Matrix,
    Probability,
    Scalar,
    SequencePath,
    Statistics,
    Transport,
    Vector,
}

internal readonly record struct MathBlockGpuFeature(string Identity, MathBlockGpuFamily Family, int Opcode);

internal static class MathBlockGpuFeatureIndex
{
    internal static IReadOnlyCollection<string> SupportedIdentities { get; } =
    [
        BooleanVectorAllV1BlockGpu.Identity,
        BooleanVectorAndV1BlockGpu.Identity,
        BooleanVectorAnyV1BlockGpu.Identity,
        BooleanVectorNotV1BlockGpu.Identity,
        BooleanVectorOrV1BlockGpu.Identity,
        BooleanVectorTrueCountV1BlockGpu.Identity,
        BooleanVectorTrueIndicesV1BlockGpu.Identity,
        BooleanVectorXorV1BlockGpu.Identity,
        BooleanAndV1BlockGpu.Identity,
        BooleanNotV1BlockGpu.Identity,
        BooleanOrV1BlockGpu.Identity,
        BooleanXorV1BlockGpu.Identity,
        CapacityChoquetIntegralV1BlockGpu.Identity,
        CapacityIsSubmodularV1BlockGpu.Identity,
        CapacityMobiusTransformV1BlockGpu.Identity,
        CombinatoricsBallotCountV1BlockGpu.Identity,
        CombinatoricsBinomialCoefficientV1BlockGpu.Identity,
        CombinatoricsFactorialV1BlockGpu.Identity,
        CombinatoricsNonemptySubsetSumsV1BlockGpu.Identity,
        ComplexMatrixPickV1BlockGpu.Identity,
        ComplexVectorCreateV1BlockGpu.Identity,
        ComplexVectorImaginaryV1BlockGpu.Identity,
        ComplexVectorMagnitudeV1BlockGpu.Identity,
        ComplexVectorRealV1BlockGpu.Identity,
        ComplexAddV1BlockGpu.Identity,
        ComplexConjugateV1BlockGpu.Identity,
        ComplexCreateV1BlockGpu.Identity,
        ComplexDivideV1BlockGpu.Identity,
        ComplexExponentialV1BlockGpu.Identity,
        ComplexFromPolarV1BlockGpu.Identity,
        ComplexMagnitudeV1BlockGpu.Identity,
        ComplexMultiplyV1BlockGpu.Identity,
        ComplexNaturalLogarithmV1BlockGpu.Identity,
        ComplexNegateV1BlockGpu.Identity,
        ComplexPhaseV1BlockGpu.Identity,
        ComplexPowerV1BlockGpu.Identity,
        ComplexSquareRootV1BlockGpu.Identity,
        ComplexSubtractV1BlockGpu.Identity,
        CooperativeShapleyValuesV1BlockGpu.Identity,
        ExtensionMcshaneV1BlockGpu.Identity,
        ExtensionWhitneyV1BlockGpu.Identity,
        GeometryBarycentricCoordinatesV1BlockGpu.Identity,
        GeometryCentroidV1BlockGpu.Identity,
        GeometryCircumradiusV1BlockGpu.Identity,
        GeometryContainsPointV1BlockGpu.Identity,
        GeometryConvexHullV1BlockGpu.Identity,
        GeometryDelaunayGraphV1BlockGpu.Identity,
        GeometryDiameterV1BlockGpu.Identity,
        GeometryDiscreteFrechetDistanceV1BlockGpu.Identity,
        GeometryDistanceV1BlockGpu.Identity,
        GeometryFisherRaoDistanceV1BlockGpu.Identity,
        GeometryGabrielGraphV1BlockGpu.Identity,
        GeometryHalfspaceDepthV1BlockGpu.Identity,
        GeometryHausdorffDistanceV1BlockGpu.Identity,
        GeometryPathLengthV1BlockGpu.Identity,
        GeometryPerimeterV1BlockGpu.Identity,
        GeometryPointToSegmentDistanceV1BlockGpu.Identity,
        GeometryPolygonAreaV1BlockGpu.Identity,
        GeometrySignedPolygonAreaV1BlockGpu.Identity,
        GeometrySimplicialDepthV1BlockGpu.Identity,
        GraphAlgebraicConnectivityV1BlockGpu.Identity,
        GraphConductanceV1BlockGpu.Identity,
        GraphConnectedComponentCountV1BlockGpu.Identity,
        GraphDegreeV1BlockGpu.Identity,
        GraphFromDirectedAdjacencyV1BlockGpu.Identity,
        GraphHodgePotentialV1BlockGpu.Identity,
        GraphHodgeResidualNormV1BlockGpu.Identity,
        GraphIsConnectedV1BlockGpu.Identity,
        GraphMinimumSpanningForestV1BlockGpu.Identity,
        GraphPageRankV1BlockGpu.Identity,
        GraphToDirectedAdjacencyV1BlockGpu.Identity,
        GraphTriangleCountV1BlockGpu.Identity,
        GraphUndirectedAdjacencyMatrixV1BlockGpu.Identity,
        GraphUndirectedLaplacianV1BlockGpu.Identity,
        GraphUndirectedShortestPathsV1BlockGpu.Identity,
        GraphWeightedDegreeV1BlockGpu.Identity,
        InequalityGiniCoefficientV1BlockGpu.Identity,
        InequalityLorenzCurveV1BlockGpu.Identity,
        InformationBhattacharyyaCoefficientV1BlockGpu.Identity,
        InformationBinaryShannonEntropyV1BlockGpu.Identity,
        InformationConditionalMutualInformationV1BlockGpu.Identity,
        InformationCrossEntropyV1BlockGpu.Identity,
        InformationGiniImpurityV1BlockGpu.Identity,
        InformationHellingerDistanceV1BlockGpu.Identity,
        InformationJensenShannonV1BlockGpu.Identity,
        InformationKullbackLeiblerV1BlockGpu.Identity,
        InformationMutualInformationV1BlockGpu.Identity,
        InformationRenyiEntropyV1BlockGpu.Identity,
        InformationShannonEntropyV1BlockGpu.Identity,
        InformationTotalVariationDistanceV1BlockGpu.Identity,
        InformationTsallisEntropyV1BlockGpu.Identity,
        MarkovEntropyProductionV1BlockGpu.Identity,
        MarkovStationaryDistributionV1BlockGpu.Identity,
        MatrixAddV1BlockGpu.Identity,
        MatrixAppendRowV1BlockGpu.Identity,
        MatrixColumnSumsV1BlockGpu.Identity,
        MatrixColumnV1BlockGpu.Identity,
        MatrixCommutatorV1BlockGpu.Identity,
        MatrixDeterminantV1BlockGpu.Identity,
        MatrixDiagonalFromVectorV1BlockGpu.Identity,
        MatrixDiagonalV1BlockGpu.Identity,
        MatrixExponentialV1BlockGpu.Identity,
        MatrixFlattenV1BlockGpu.Identity,
        MatrixFrobeniusNormV1BlockGpu.Identity,
        MatrixGramV1BlockGpu.Identity,
        MatrixHadamardProductV1BlockGpu.Identity,
        MatrixHankelV1BlockGpu.Identity,
        MatrixIdentityV1BlockGpu.Identity,
        MatrixIntegerPowerV1BlockGpu.Identity,
        MatrixInverseV1BlockGpu.Identity,
        MatrixIsPositiveDefiniteV1BlockGpu.Identity,
        MatrixIsSymmetricV1BlockGpu.Identity,
        MatrixIsTotallyNonnegativeV1BlockGpu.Identity,
        MatrixKroneckerProductV1BlockGpu.Identity,
        MatrixLargestSymmetricEigenvalueV1BlockGpu.Identity,
        MatrixMaximalMinorsV1BlockGpu.Identity,
        MatrixMultiplyVectorV1BlockGpu.Identity,
        MatrixMultiplyV1BlockGpu.Identity,
        MatrixOuterProductV1BlockGpu.Identity,
        MatrixPerronValueV1BlockGpu.Identity,
        MatrixPerronVectorV1BlockGpu.Identity,
        MatrixPrincipalMinorsV1BlockGpu.Identity,
        MatrixRankV1BlockGpu.Identity,
        MatrixReshapeV1BlockGpu.Identity,
        MatrixRowSumsV1BlockGpu.Identity,
        MatrixRowV1BlockGpu.Identity,
        MatrixScaleV1BlockGpu.Identity,
        MatrixSchurComplementV1BlockGpu.Identity,
        MatrixSmallestSymmetricEigenvalueV1BlockGpu.Identity,
        MatrixSolveV1BlockGpu.Identity,
        MatrixSpectralNormV1BlockGpu.Identity,
        MatrixStackRowsV1BlockGpu.Identity,
        MatrixSubtractV1BlockGpu.Identity,
        MatrixSymmetricEigenvaluesV1BlockGpu.Identity,
        MatrixToeplitzV1BlockGpu.Identity,
        MatrixTraceV1BlockGpu.Identity,
        MatrixTransposeV1BlockGpu.Identity,
        OrderIsotonicRegressionV1BlockGpu.Identity,
        OrderMajorizesV1BlockGpu.Identity,
        PathCumulativeDeviationV1BlockGpu.Identity,
        PathDynamicTimeWarpingV1BlockGpu.Identity,
        PathFirstPassageIndexV1BlockGpu.Identity,
        PathHysteresisV1BlockGpu.Identity,
        PathLeadLagTransformV1BlockGpu.Identity,
        PathLongestTrueRunV1BlockGpu.Identity,
        PathMaximumDeclineV1BlockGpu.Identity,
        PathMaximumRelativeDeclineV1BlockGpu.Identity,
        PathPowerVariationV1BlockGpu.Identity,
        PathQuadraticVariationV1BlockGpu.Identity,
        PathRecurrenceRateV1BlockGpu.Identity,
        PathReflectedCumulativeSumV1BlockGpu.Identity,
        PathRunLengthEncodeV1BlockGpu.Identity,
        PathSignatureLevelOneV1BlockGpu.Identity,
        PathSignatureLevelThreeV1BlockGpu.Identity,
        PathSignatureLevelTwoV1BlockGpu.Identity,
        PathTotalVariationV1BlockGpu.Identity,
        PathTurningPointCountV1BlockGpu.Identity,
        PathZeroCrossingCountV1BlockGpu.Identity,
        PointSetFromMatrixV1BlockGpu.Identity,
        PointSetToMatrixV1BlockGpu.Identity,
        PolynomialBernsteinEvaluateV1BlockGpu.Identity,
        PolynomialCubicRootsV1BlockGpu.Identity,
        PolynomialDerivativeV1BlockGpu.Identity,
        PolynomialElementarySymmetricV1BlockGpu.Identity,
        PolynomialEvaluateV1BlockGpu.Identity,
        ProbabilityLogSumExpV1BlockGpu.Identity,
        ProbabilityNormalCdfV1BlockGpu.Identity,
        ProbabilityNormalizeV1BlockGpu.Identity,
        ProbabilityPoissonCdfV1BlockGpu.Identity,
        ProbabilityPoissonPmfV1BlockGpu.Identity,
        ProbabilitySoftmaxV1BlockGpu.Identity,
        ProjectiveHilbertDistanceV1BlockGpu.Identity,
        ScalarAbsoluteV1BlockGpu.Identity,
        ScalarAddV1BlockGpu.Identity,
        ScalarArcCosineV1BlockGpu.Identity,
        ScalarArcSineV1BlockGpu.Identity,
        ScalarArcTangent2V1BlockGpu.Identity,
        ScalarArcTangentV1BlockGpu.Identity,
        ScalarBinaryLogarithmV1BlockGpu.Identity,
        ScalarCeilingV1BlockGpu.Identity,
        ScalarClampV1BlockGpu.Identity,
        ScalarCommonLogarithmV1BlockGpu.Identity,
        ScalarCosineV1BlockGpu.Identity,
        ScalarCubeRootV1BlockGpu.Identity,
        ScalarCubeV1BlockGpu.Identity,
        ScalarDivideV1BlockGpu.Identity,
        ScalarEqualV1BlockGpu.Identity,
        ScalarExponentialV1BlockGpu.Identity,
        ScalarFloorV1BlockGpu.Identity,
        ScalarGreaterOrEqualV1BlockGpu.Identity,
        ScalarGreaterThanV1BlockGpu.Identity,
        ScalarHyperbolicCosineV1BlockGpu.Identity,
        ScalarHyperbolicSineV1BlockGpu.Identity,
        ScalarHyperbolicTangentV1BlockGpu.Identity,
        ScalarInverseHyperbolicCosineV1BlockGpu.Identity,
        ScalarInverseHyperbolicSineV1BlockGpu.Identity,
        ScalarInverseHyperbolicTangentV1BlockGpu.Identity,
        ScalarLessOrEqualV1BlockGpu.Identity,
        ScalarLessThanV1BlockGpu.Identity,
        ScalarLogOnePlusV1BlockGpu.Identity,
        ScalarLogisticV1BlockGpu.Identity,
        ScalarLogitV1BlockGpu.Identity,
        ScalarMaximumV1BlockGpu.Identity,
        ScalarMinimumV1BlockGpu.Identity,
        ScalarModuloV1BlockGpu.Identity,
        ScalarMultiplyV1BlockGpu.Identity,
        ScalarNaturalLogarithmV1BlockGpu.Identity,
        ScalarNegateV1BlockGpu.Identity,
        ScalarNotEqualV1BlockGpu.Identity,
        ScalarPositivePartV1BlockGpu.Identity,
        ScalarPowerV1BlockGpu.Identity,
        ScalarReciprocalV1BlockGpu.Identity,
        ScalarRoundV1BlockGpu.Identity,
        ScalarSelectV1BlockGpu.Identity,
        ScalarSignV1BlockGpu.Identity,
        ScalarSineV1BlockGpu.Identity,
        ScalarSoftplusV1BlockGpu.Identity,
        ScalarSquareRootV1BlockGpu.Identity,
        ScalarSquareV1BlockGpu.Identity,
        ScalarSubtractV1BlockGpu.Identity,
        ScalarTangentV1BlockGpu.Identity,
        ScalarTruncateV1BlockGpu.Identity,
        SequenceConvolutionV1BlockGpu.Identity,
        SequenceDifferenceV1BlockGpu.Identity,
        SequenceExponentialMovingAverageV1BlockGpu.Identity,
        SequenceRollingMaximumV1BlockGpu.Identity,
        SequenceRollingMeanV1BlockGpu.Identity,
        SequenceRollingMedianV1BlockGpu.Identity,
        SequenceRollingMinimumV1BlockGpu.Identity,
        SequenceRollingQuantileV1BlockGpu.Identity,
        SequenceRollingStandardDeviationV1BlockGpu.Identity,
        SequenceRollingSumV1BlockGpu.Identity,
        SequenceRollingVarianceV1BlockGpu.Identity,
        ShapeGreatestConvexMinorantV1BlockGpu.Identity,
        ShapeIsCompletelyMonotoneV1BlockGpu.Identity,
        ShapeIsLogConcaveV1BlockGpu.Identity,
        ShapeLeastConcaveMajorantV1BlockGpu.Identity,
        SpecialBetaV1BlockGpu.Identity,
        SpecialErrorFunctionV1BlockGpu.Identity,
        SpecialLogGammaV1BlockGpu.Identity,
        SpecialRegularizedIncompleteBetaV1BlockGpu.Identity,
        StateTransitionCountsV1BlockGpu.Identity,
        StatisticsAutocorrelationV1BlockGpu.Identity,
        StatisticsCentralMomentV1BlockGpu.Identity,
        StatisticsCovarianceMatrixV1BlockGpu.Identity,
        StatisticsDistanceCorrelationV1BlockGpu.Identity,
        StatisticsHistogramV1BlockGpu.Identity,
        StatisticsInterquartileRangeV1BlockGpu.Identity,
        StatisticsKendallTauBV1BlockGpu.Identity,
        StatisticsLinearInterceptV1BlockGpu.Identity,
        StatisticsLinearRSquaredV1BlockGpu.Identity,
        StatisticsLinearSlopeV1BlockGpu.Identity,
        StatisticsMedianAbsoluteDeviationV1BlockGpu.Identity,
        StatisticsPearsonCorrelationV1BlockGpu.Identity,
        StatisticsPopulationCovarianceV1BlockGpu.Identity,
        StatisticsPopulationExcessKurtosisV1BlockGpu.Identity,
        StatisticsPopulationSkewnessV1BlockGpu.Identity,
        StatisticsPopulationStandardDeviationV1BlockGpu.Identity,
        StatisticsPopulationVarianceV1BlockGpu.Identity,
        StatisticsPseudomedianV1BlockGpu.Identity,
        StatisticsRawMomentV1BlockGpu.Identity,
        StatisticsRootMeanSquareV1BlockGpu.Identity,
        StatisticsSampleCovarianceV1BlockGpu.Identity,
        StatisticsSampleStandardDeviationV1BlockGpu.Identity,
        StatisticsSampleVarianceV1BlockGpu.Identity,
        StatisticsSpearmanCorrelationV1BlockGpu.Identity,
        StatisticsTheilSenSlopeV1BlockGpu.Identity,
        StatisticsWeightedMeanV1BlockGpu.Identity,
        StatisticsWeightedPopulationVarianceV1BlockGpu.Identity,
        SurvivalDiscreteHazardV1BlockGpu.Identity,
        SurvivalProductLimitV1BlockGpu.Identity,
        TopologyZeroDimensionalPersistenceV1BlockGpu.Identity,
        TransformDiscreteFourierV1BlockGpu.Identity,
        TransformHaarV1BlockGpu.Identity,
        TransformInverseDiscreteFourierV1BlockGpu.Identity,
        TransformWalshHadamardV1BlockGpu.Identity,
        TransportAssignmentCostV1BlockGpu.Identity,
        TransportCouplingCostV1BlockGpu.Identity,
        TransportEnergyDistanceV1BlockGpu.Identity,
        TransportMinimumAssignmentV1BlockGpu.Identity,
        TransportMonotoneCouplingV1BlockGpu.Identity,
        TransportOrderedEarthMoverV1BlockGpu.Identity,
        TransportSinkhornCouplingV1BlockGpu.Identity,
        TransportUniformWassersteinV1BlockGpu.Identity,
        TransportWeightedWasserstein1V1BlockGpu.Identity,
        TropicalMaxPlusMultiplyV1BlockGpu.Identity,
        TropicalMinPlusMultiplyV1BlockGpu.Identity,
        VectorAbsoluteV1BlockGpu.Identity,
        VectorAddScalarV1BlockGpu.Identity,
        VectorAddV1BlockGpu.Identity,
        VectorAppendV1BlockGpu.Identity,
        VectorArgMaximumV1BlockGpu.Identity,
        VectorArgMinimumV1BlockGpu.Identity,
        VectorConcatenateV1BlockGpu.Identity,
        VectorCumulativeProductV1BlockGpu.Identity,
        VectorCumulativeSumV1BlockGpu.Identity,
        VectorDivideV1BlockGpu.Identity,
        VectorDotV1BlockGpu.Identity,
        VectorEqualV1BlockGpu.Identity,
        VectorExponentialV1BlockGpu.Identity,
        VectorGatherV1BlockGpu.Identity,
        VectorGeometricMeanV1BlockGpu.Identity,
        VectorGreaterThanV1BlockGpu.Identity,
        VectorIndexV1BlockGpu.Identity,
        VectorL1NormV1BlockGpu.Identity,
        VectorL2NormV1BlockGpu.Identity,
        VectorLengthV1BlockGpu.Identity,
        VectorLessThanV1BlockGpu.Identity,
        VectorLinspaceV1BlockGpu.Identity,
        VectorMaximumV1BlockGpu.Identity,
        VectorMeanV1BlockGpu.Identity,
        VectorMedianV1BlockGpu.Identity,
        VectorMinimumV1BlockGpu.Identity,
        VectorMultiplyV1BlockGpu.Identity,
        VectorNaturalLogarithmV1BlockGpu.Identity,
        VectorNormalizeL1V1BlockGpu.Identity,
        VectorNormalizeL2V1BlockGpu.Identity,
        VectorPairV1BlockGpu.Identity,
        VectorPositivePartV1BlockGpu.Identity,
        VectorPowerV1BlockGpu.Identity,
        VectorPrependV1BlockGpu.Identity,
        VectorProductV1BlockGpu.Identity,
        VectorQuantileV1BlockGpu.Identity,
        VectorRankV1BlockGpu.Identity,
        VectorRepeatV1BlockGpu.Identity,
        VectorReverseV1BlockGpu.Identity,
        VectorScaleV1BlockGpu.Identity,
        VectorSelectV1BlockGpu.Identity,
        VectorSignV1BlockGpu.Identity,
        VectorSliceV1BlockGpu.Identity,
        VectorSortV1BlockGpu.Identity,
        VectorSquareRootV1BlockGpu.Identity,
        VectorSquareV1BlockGpu.Identity,
        VectorStandardizeV1BlockGpu.Identity,
        VectorSubtractV1BlockGpu.Identity,
        VectorSumV1BlockGpu.Identity,
        VectorUniqueV1BlockGpu.Identity,
    ];

    internal static MathBlockGpuFeature Resolve(string identity) => identity switch
    {
        BooleanVectorAllV1BlockGpu.Identity => BooleanVectorAllV1BlockGpu.Feature,
        BooleanVectorAndV1BlockGpu.Identity => BooleanVectorAndV1BlockGpu.Feature,
        BooleanVectorAnyV1BlockGpu.Identity => BooleanVectorAnyV1BlockGpu.Feature,
        BooleanVectorNotV1BlockGpu.Identity => BooleanVectorNotV1BlockGpu.Feature,
        BooleanVectorOrV1BlockGpu.Identity => BooleanVectorOrV1BlockGpu.Feature,
        BooleanVectorTrueCountV1BlockGpu.Identity => BooleanVectorTrueCountV1BlockGpu.Feature,
        BooleanVectorTrueIndicesV1BlockGpu.Identity => BooleanVectorTrueIndicesV1BlockGpu.Feature,
        BooleanVectorXorV1BlockGpu.Identity => BooleanVectorXorV1BlockGpu.Feature,
        BooleanAndV1BlockGpu.Identity => BooleanAndV1BlockGpu.Feature,
        BooleanNotV1BlockGpu.Identity => BooleanNotV1BlockGpu.Feature,
        BooleanOrV1BlockGpu.Identity => BooleanOrV1BlockGpu.Feature,
        BooleanXorV1BlockGpu.Identity => BooleanXorV1BlockGpu.Feature,
        CapacityChoquetIntegralV1BlockGpu.Identity => CapacityChoquetIntegralV1BlockGpu.Feature,
        CapacityIsSubmodularV1BlockGpu.Identity => CapacityIsSubmodularV1BlockGpu.Feature,
        CapacityMobiusTransformV1BlockGpu.Identity => CapacityMobiusTransformV1BlockGpu.Feature,
        CombinatoricsBallotCountV1BlockGpu.Identity => CombinatoricsBallotCountV1BlockGpu.Feature,
        CombinatoricsBinomialCoefficientV1BlockGpu.Identity => CombinatoricsBinomialCoefficientV1BlockGpu.Feature,
        CombinatoricsFactorialV1BlockGpu.Identity => CombinatoricsFactorialV1BlockGpu.Feature,
        CombinatoricsNonemptySubsetSumsV1BlockGpu.Identity => CombinatoricsNonemptySubsetSumsV1BlockGpu.Feature,
        ComplexMatrixPickV1BlockGpu.Identity => ComplexMatrixPickV1BlockGpu.Feature,
        ComplexVectorCreateV1BlockGpu.Identity => ComplexVectorCreateV1BlockGpu.Feature,
        ComplexVectorImaginaryV1BlockGpu.Identity => ComplexVectorImaginaryV1BlockGpu.Feature,
        ComplexVectorMagnitudeV1BlockGpu.Identity => ComplexVectorMagnitudeV1BlockGpu.Feature,
        ComplexVectorRealV1BlockGpu.Identity => ComplexVectorRealV1BlockGpu.Feature,
        ComplexAddV1BlockGpu.Identity => ComplexAddV1BlockGpu.Feature,
        ComplexConjugateV1BlockGpu.Identity => ComplexConjugateV1BlockGpu.Feature,
        ComplexCreateV1BlockGpu.Identity => ComplexCreateV1BlockGpu.Feature,
        ComplexDivideV1BlockGpu.Identity => ComplexDivideV1BlockGpu.Feature,
        ComplexExponentialV1BlockGpu.Identity => ComplexExponentialV1BlockGpu.Feature,
        ComplexFromPolarV1BlockGpu.Identity => ComplexFromPolarV1BlockGpu.Feature,
        ComplexMagnitudeV1BlockGpu.Identity => ComplexMagnitudeV1BlockGpu.Feature,
        ComplexMultiplyV1BlockGpu.Identity => ComplexMultiplyV1BlockGpu.Feature,
        ComplexNaturalLogarithmV1BlockGpu.Identity => ComplexNaturalLogarithmV1BlockGpu.Feature,
        ComplexNegateV1BlockGpu.Identity => ComplexNegateV1BlockGpu.Feature,
        ComplexPhaseV1BlockGpu.Identity => ComplexPhaseV1BlockGpu.Feature,
        ComplexPowerV1BlockGpu.Identity => ComplexPowerV1BlockGpu.Feature,
        ComplexSquareRootV1BlockGpu.Identity => ComplexSquareRootV1BlockGpu.Feature,
        ComplexSubtractV1BlockGpu.Identity => ComplexSubtractV1BlockGpu.Feature,
        CooperativeShapleyValuesV1BlockGpu.Identity => CooperativeShapleyValuesV1BlockGpu.Feature,
        ExtensionMcshaneV1BlockGpu.Identity => ExtensionMcshaneV1BlockGpu.Feature,
        ExtensionWhitneyV1BlockGpu.Identity => ExtensionWhitneyV1BlockGpu.Feature,
        GeometryBarycentricCoordinatesV1BlockGpu.Identity => GeometryBarycentricCoordinatesV1BlockGpu.Feature,
        GeometryCentroidV1BlockGpu.Identity => GeometryCentroidV1BlockGpu.Feature,
        GeometryCircumradiusV1BlockGpu.Identity => GeometryCircumradiusV1BlockGpu.Feature,
        GeometryContainsPointV1BlockGpu.Identity => GeometryContainsPointV1BlockGpu.Feature,
        GeometryConvexHullV1BlockGpu.Identity => GeometryConvexHullV1BlockGpu.Feature,
        GeometryDelaunayGraphV1BlockGpu.Identity => GeometryDelaunayGraphV1BlockGpu.Feature,
        GeometryDiameterV1BlockGpu.Identity => GeometryDiameterV1BlockGpu.Feature,
        GeometryDiscreteFrechetDistanceV1BlockGpu.Identity => GeometryDiscreteFrechetDistanceV1BlockGpu.Feature,
        GeometryDistanceV1BlockGpu.Identity => GeometryDistanceV1BlockGpu.Feature,
        GeometryFisherRaoDistanceV1BlockGpu.Identity => GeometryFisherRaoDistanceV1BlockGpu.Feature,
        GeometryGabrielGraphV1BlockGpu.Identity => GeometryGabrielGraphV1BlockGpu.Feature,
        GeometryHalfspaceDepthV1BlockGpu.Identity => GeometryHalfspaceDepthV1BlockGpu.Feature,
        GeometryHausdorffDistanceV1BlockGpu.Identity => GeometryHausdorffDistanceV1BlockGpu.Feature,
        GeometryPathLengthV1BlockGpu.Identity => GeometryPathLengthV1BlockGpu.Feature,
        GeometryPerimeterV1BlockGpu.Identity => GeometryPerimeterV1BlockGpu.Feature,
        GeometryPointToSegmentDistanceV1BlockGpu.Identity => GeometryPointToSegmentDistanceV1BlockGpu.Feature,
        GeometryPolygonAreaV1BlockGpu.Identity => GeometryPolygonAreaV1BlockGpu.Feature,
        GeometrySignedPolygonAreaV1BlockGpu.Identity => GeometrySignedPolygonAreaV1BlockGpu.Feature,
        GeometrySimplicialDepthV1BlockGpu.Identity => GeometrySimplicialDepthV1BlockGpu.Feature,
        GraphAlgebraicConnectivityV1BlockGpu.Identity => GraphAlgebraicConnectivityV1BlockGpu.Feature,
        GraphConductanceV1BlockGpu.Identity => GraphConductanceV1BlockGpu.Feature,
        GraphConnectedComponentCountV1BlockGpu.Identity => GraphConnectedComponentCountV1BlockGpu.Feature,
        GraphDegreeV1BlockGpu.Identity => GraphDegreeV1BlockGpu.Feature,
        GraphFromDirectedAdjacencyV1BlockGpu.Identity => GraphFromDirectedAdjacencyV1BlockGpu.Feature,
        GraphHodgePotentialV1BlockGpu.Identity => GraphHodgePotentialV1BlockGpu.Feature,
        GraphHodgeResidualNormV1BlockGpu.Identity => GraphHodgeResidualNormV1BlockGpu.Feature,
        GraphIsConnectedV1BlockGpu.Identity => GraphIsConnectedV1BlockGpu.Feature,
        GraphMinimumSpanningForestV1BlockGpu.Identity => GraphMinimumSpanningForestV1BlockGpu.Feature,
        GraphPageRankV1BlockGpu.Identity => GraphPageRankV1BlockGpu.Feature,
        GraphToDirectedAdjacencyV1BlockGpu.Identity => GraphToDirectedAdjacencyV1BlockGpu.Feature,
        GraphTriangleCountV1BlockGpu.Identity => GraphTriangleCountV1BlockGpu.Feature,
        GraphUndirectedAdjacencyMatrixV1BlockGpu.Identity => GraphUndirectedAdjacencyMatrixV1BlockGpu.Feature,
        GraphUndirectedLaplacianV1BlockGpu.Identity => GraphUndirectedLaplacianV1BlockGpu.Feature,
        GraphUndirectedShortestPathsV1BlockGpu.Identity => GraphUndirectedShortestPathsV1BlockGpu.Feature,
        GraphWeightedDegreeV1BlockGpu.Identity => GraphWeightedDegreeV1BlockGpu.Feature,
        InequalityGiniCoefficientV1BlockGpu.Identity => InequalityGiniCoefficientV1BlockGpu.Feature,
        InequalityLorenzCurveV1BlockGpu.Identity => InequalityLorenzCurveV1BlockGpu.Feature,
        InformationBhattacharyyaCoefficientV1BlockGpu.Identity => InformationBhattacharyyaCoefficientV1BlockGpu.Feature,
        InformationBinaryShannonEntropyV1BlockGpu.Identity => InformationBinaryShannonEntropyV1BlockGpu.Feature,
        InformationConditionalMutualInformationV1BlockGpu.Identity => InformationConditionalMutualInformationV1BlockGpu.Feature,
        InformationCrossEntropyV1BlockGpu.Identity => InformationCrossEntropyV1BlockGpu.Feature,
        InformationGiniImpurityV1BlockGpu.Identity => InformationGiniImpurityV1BlockGpu.Feature,
        InformationHellingerDistanceV1BlockGpu.Identity => InformationHellingerDistanceV1BlockGpu.Feature,
        InformationJensenShannonV1BlockGpu.Identity => InformationJensenShannonV1BlockGpu.Feature,
        InformationKullbackLeiblerV1BlockGpu.Identity => InformationKullbackLeiblerV1BlockGpu.Feature,
        InformationMutualInformationV1BlockGpu.Identity => InformationMutualInformationV1BlockGpu.Feature,
        InformationRenyiEntropyV1BlockGpu.Identity => InformationRenyiEntropyV1BlockGpu.Feature,
        InformationShannonEntropyV1BlockGpu.Identity => InformationShannonEntropyV1BlockGpu.Feature,
        InformationTotalVariationDistanceV1BlockGpu.Identity => InformationTotalVariationDistanceV1BlockGpu.Feature,
        InformationTsallisEntropyV1BlockGpu.Identity => InformationTsallisEntropyV1BlockGpu.Feature,
        MarkovEntropyProductionV1BlockGpu.Identity => MarkovEntropyProductionV1BlockGpu.Feature,
        MarkovStationaryDistributionV1BlockGpu.Identity => MarkovStationaryDistributionV1BlockGpu.Feature,
        MatrixAddV1BlockGpu.Identity => MatrixAddV1BlockGpu.Feature,
        MatrixAppendRowV1BlockGpu.Identity => MatrixAppendRowV1BlockGpu.Feature,
        MatrixColumnSumsV1BlockGpu.Identity => MatrixColumnSumsV1BlockGpu.Feature,
        MatrixColumnV1BlockGpu.Identity => MatrixColumnV1BlockGpu.Feature,
        MatrixCommutatorV1BlockGpu.Identity => MatrixCommutatorV1BlockGpu.Feature,
        MatrixDeterminantV1BlockGpu.Identity => MatrixDeterminantV1BlockGpu.Feature,
        MatrixDiagonalFromVectorV1BlockGpu.Identity => MatrixDiagonalFromVectorV1BlockGpu.Feature,
        MatrixDiagonalV1BlockGpu.Identity => MatrixDiagonalV1BlockGpu.Feature,
        MatrixExponentialV1BlockGpu.Identity => MatrixExponentialV1BlockGpu.Feature,
        MatrixFlattenV1BlockGpu.Identity => MatrixFlattenV1BlockGpu.Feature,
        MatrixFrobeniusNormV1BlockGpu.Identity => MatrixFrobeniusNormV1BlockGpu.Feature,
        MatrixGramV1BlockGpu.Identity => MatrixGramV1BlockGpu.Feature,
        MatrixHadamardProductV1BlockGpu.Identity => MatrixHadamardProductV1BlockGpu.Feature,
        MatrixHankelV1BlockGpu.Identity => MatrixHankelV1BlockGpu.Feature,
        MatrixIdentityV1BlockGpu.Identity => MatrixIdentityV1BlockGpu.Feature,
        MatrixIntegerPowerV1BlockGpu.Identity => MatrixIntegerPowerV1BlockGpu.Feature,
        MatrixInverseV1BlockGpu.Identity => MatrixInverseV1BlockGpu.Feature,
        MatrixIsPositiveDefiniteV1BlockGpu.Identity => MatrixIsPositiveDefiniteV1BlockGpu.Feature,
        MatrixIsSymmetricV1BlockGpu.Identity => MatrixIsSymmetricV1BlockGpu.Feature,
        MatrixIsTotallyNonnegativeV1BlockGpu.Identity => MatrixIsTotallyNonnegativeV1BlockGpu.Feature,
        MatrixKroneckerProductV1BlockGpu.Identity => MatrixKroneckerProductV1BlockGpu.Feature,
        MatrixLargestSymmetricEigenvalueV1BlockGpu.Identity => MatrixLargestSymmetricEigenvalueV1BlockGpu.Feature,
        MatrixMaximalMinorsV1BlockGpu.Identity => MatrixMaximalMinorsV1BlockGpu.Feature,
        MatrixMultiplyVectorV1BlockGpu.Identity => MatrixMultiplyVectorV1BlockGpu.Feature,
        MatrixMultiplyV1BlockGpu.Identity => MatrixMultiplyV1BlockGpu.Feature,
        MatrixOuterProductV1BlockGpu.Identity => MatrixOuterProductV1BlockGpu.Feature,
        MatrixPerronValueV1BlockGpu.Identity => MatrixPerronValueV1BlockGpu.Feature,
        MatrixPerronVectorV1BlockGpu.Identity => MatrixPerronVectorV1BlockGpu.Feature,
        MatrixPrincipalMinorsV1BlockGpu.Identity => MatrixPrincipalMinorsV1BlockGpu.Feature,
        MatrixRankV1BlockGpu.Identity => MatrixRankV1BlockGpu.Feature,
        MatrixReshapeV1BlockGpu.Identity => MatrixReshapeV1BlockGpu.Feature,
        MatrixRowSumsV1BlockGpu.Identity => MatrixRowSumsV1BlockGpu.Feature,
        MatrixRowV1BlockGpu.Identity => MatrixRowV1BlockGpu.Feature,
        MatrixScaleV1BlockGpu.Identity => MatrixScaleV1BlockGpu.Feature,
        MatrixSchurComplementV1BlockGpu.Identity => MatrixSchurComplementV1BlockGpu.Feature,
        MatrixSmallestSymmetricEigenvalueV1BlockGpu.Identity => MatrixSmallestSymmetricEigenvalueV1BlockGpu.Feature,
        MatrixSolveV1BlockGpu.Identity => MatrixSolveV1BlockGpu.Feature,
        MatrixSpectralNormV1BlockGpu.Identity => MatrixSpectralNormV1BlockGpu.Feature,
        MatrixStackRowsV1BlockGpu.Identity => MatrixStackRowsV1BlockGpu.Feature,
        MatrixSubtractV1BlockGpu.Identity => MatrixSubtractV1BlockGpu.Feature,
        MatrixSymmetricEigenvaluesV1BlockGpu.Identity => MatrixSymmetricEigenvaluesV1BlockGpu.Feature,
        MatrixToeplitzV1BlockGpu.Identity => MatrixToeplitzV1BlockGpu.Feature,
        MatrixTraceV1BlockGpu.Identity => MatrixTraceV1BlockGpu.Feature,
        MatrixTransposeV1BlockGpu.Identity => MatrixTransposeV1BlockGpu.Feature,
        OrderIsotonicRegressionV1BlockGpu.Identity => OrderIsotonicRegressionV1BlockGpu.Feature,
        OrderMajorizesV1BlockGpu.Identity => OrderMajorizesV1BlockGpu.Feature,
        PathCumulativeDeviationV1BlockGpu.Identity => PathCumulativeDeviationV1BlockGpu.Feature,
        PathDynamicTimeWarpingV1BlockGpu.Identity => PathDynamicTimeWarpingV1BlockGpu.Feature,
        PathFirstPassageIndexV1BlockGpu.Identity => PathFirstPassageIndexV1BlockGpu.Feature,
        PathHysteresisV1BlockGpu.Identity => PathHysteresisV1BlockGpu.Feature,
        PathLeadLagTransformV1BlockGpu.Identity => PathLeadLagTransformV1BlockGpu.Feature,
        PathLongestTrueRunV1BlockGpu.Identity => PathLongestTrueRunV1BlockGpu.Feature,
        PathMaximumDeclineV1BlockGpu.Identity => PathMaximumDeclineV1BlockGpu.Feature,
        PathMaximumRelativeDeclineV1BlockGpu.Identity => PathMaximumRelativeDeclineV1BlockGpu.Feature,
        PathPowerVariationV1BlockGpu.Identity => PathPowerVariationV1BlockGpu.Feature,
        PathQuadraticVariationV1BlockGpu.Identity => PathQuadraticVariationV1BlockGpu.Feature,
        PathRecurrenceRateV1BlockGpu.Identity => PathRecurrenceRateV1BlockGpu.Feature,
        PathReflectedCumulativeSumV1BlockGpu.Identity => PathReflectedCumulativeSumV1BlockGpu.Feature,
        PathRunLengthEncodeV1BlockGpu.Identity => PathRunLengthEncodeV1BlockGpu.Feature,
        PathSignatureLevelOneV1BlockGpu.Identity => PathSignatureLevelOneV1BlockGpu.Feature,
        PathSignatureLevelThreeV1BlockGpu.Identity => PathSignatureLevelThreeV1BlockGpu.Feature,
        PathSignatureLevelTwoV1BlockGpu.Identity => PathSignatureLevelTwoV1BlockGpu.Feature,
        PathTotalVariationV1BlockGpu.Identity => PathTotalVariationV1BlockGpu.Feature,
        PathTurningPointCountV1BlockGpu.Identity => PathTurningPointCountV1BlockGpu.Feature,
        PathZeroCrossingCountV1BlockGpu.Identity => PathZeroCrossingCountV1BlockGpu.Feature,
        PointSetFromMatrixV1BlockGpu.Identity => PointSetFromMatrixV1BlockGpu.Feature,
        PointSetToMatrixV1BlockGpu.Identity => PointSetToMatrixV1BlockGpu.Feature,
        PolynomialBernsteinEvaluateV1BlockGpu.Identity => PolynomialBernsteinEvaluateV1BlockGpu.Feature,
        PolynomialCubicRootsV1BlockGpu.Identity => PolynomialCubicRootsV1BlockGpu.Feature,
        PolynomialDerivativeV1BlockGpu.Identity => PolynomialDerivativeV1BlockGpu.Feature,
        PolynomialElementarySymmetricV1BlockGpu.Identity => PolynomialElementarySymmetricV1BlockGpu.Feature,
        PolynomialEvaluateV1BlockGpu.Identity => PolynomialEvaluateV1BlockGpu.Feature,
        ProbabilityLogSumExpV1BlockGpu.Identity => ProbabilityLogSumExpV1BlockGpu.Feature,
        ProbabilityNormalCdfV1BlockGpu.Identity => ProbabilityNormalCdfV1BlockGpu.Feature,
        ProbabilityNormalizeV1BlockGpu.Identity => ProbabilityNormalizeV1BlockGpu.Feature,
        ProbabilityPoissonCdfV1BlockGpu.Identity => ProbabilityPoissonCdfV1BlockGpu.Feature,
        ProbabilityPoissonPmfV1BlockGpu.Identity => ProbabilityPoissonPmfV1BlockGpu.Feature,
        ProbabilitySoftmaxV1BlockGpu.Identity => ProbabilitySoftmaxV1BlockGpu.Feature,
        ProjectiveHilbertDistanceV1BlockGpu.Identity => ProjectiveHilbertDistanceV1BlockGpu.Feature,
        ScalarAbsoluteV1BlockGpu.Identity => ScalarAbsoluteV1BlockGpu.Feature,
        ScalarAddV1BlockGpu.Identity => ScalarAddV1BlockGpu.Feature,
        ScalarArcCosineV1BlockGpu.Identity => ScalarArcCosineV1BlockGpu.Feature,
        ScalarArcSineV1BlockGpu.Identity => ScalarArcSineV1BlockGpu.Feature,
        ScalarArcTangent2V1BlockGpu.Identity => ScalarArcTangent2V1BlockGpu.Feature,
        ScalarArcTangentV1BlockGpu.Identity => ScalarArcTangentV1BlockGpu.Feature,
        ScalarBinaryLogarithmV1BlockGpu.Identity => ScalarBinaryLogarithmV1BlockGpu.Feature,
        ScalarCeilingV1BlockGpu.Identity => ScalarCeilingV1BlockGpu.Feature,
        ScalarClampV1BlockGpu.Identity => ScalarClampV1BlockGpu.Feature,
        ScalarCommonLogarithmV1BlockGpu.Identity => ScalarCommonLogarithmV1BlockGpu.Feature,
        ScalarCosineV1BlockGpu.Identity => ScalarCosineV1BlockGpu.Feature,
        ScalarCubeRootV1BlockGpu.Identity => ScalarCubeRootV1BlockGpu.Feature,
        ScalarCubeV1BlockGpu.Identity => ScalarCubeV1BlockGpu.Feature,
        ScalarDivideV1BlockGpu.Identity => ScalarDivideV1BlockGpu.Feature,
        ScalarEqualV1BlockGpu.Identity => ScalarEqualV1BlockGpu.Feature,
        ScalarExponentialV1BlockGpu.Identity => ScalarExponentialV1BlockGpu.Feature,
        ScalarFloorV1BlockGpu.Identity => ScalarFloorV1BlockGpu.Feature,
        ScalarGreaterOrEqualV1BlockGpu.Identity => ScalarGreaterOrEqualV1BlockGpu.Feature,
        ScalarGreaterThanV1BlockGpu.Identity => ScalarGreaterThanV1BlockGpu.Feature,
        ScalarHyperbolicCosineV1BlockGpu.Identity => ScalarHyperbolicCosineV1BlockGpu.Feature,
        ScalarHyperbolicSineV1BlockGpu.Identity => ScalarHyperbolicSineV1BlockGpu.Feature,
        ScalarHyperbolicTangentV1BlockGpu.Identity => ScalarHyperbolicTangentV1BlockGpu.Feature,
        ScalarInverseHyperbolicCosineV1BlockGpu.Identity => ScalarInverseHyperbolicCosineV1BlockGpu.Feature,
        ScalarInverseHyperbolicSineV1BlockGpu.Identity => ScalarInverseHyperbolicSineV1BlockGpu.Feature,
        ScalarInverseHyperbolicTangentV1BlockGpu.Identity => ScalarInverseHyperbolicTangentV1BlockGpu.Feature,
        ScalarLessOrEqualV1BlockGpu.Identity => ScalarLessOrEqualV1BlockGpu.Feature,
        ScalarLessThanV1BlockGpu.Identity => ScalarLessThanV1BlockGpu.Feature,
        ScalarLogOnePlusV1BlockGpu.Identity => ScalarLogOnePlusV1BlockGpu.Feature,
        ScalarLogisticV1BlockGpu.Identity => ScalarLogisticV1BlockGpu.Feature,
        ScalarLogitV1BlockGpu.Identity => ScalarLogitV1BlockGpu.Feature,
        ScalarMaximumV1BlockGpu.Identity => ScalarMaximumV1BlockGpu.Feature,
        ScalarMinimumV1BlockGpu.Identity => ScalarMinimumV1BlockGpu.Feature,
        ScalarModuloV1BlockGpu.Identity => ScalarModuloV1BlockGpu.Feature,
        ScalarMultiplyV1BlockGpu.Identity => ScalarMultiplyV1BlockGpu.Feature,
        ScalarNaturalLogarithmV1BlockGpu.Identity => ScalarNaturalLogarithmV1BlockGpu.Feature,
        ScalarNegateV1BlockGpu.Identity => ScalarNegateV1BlockGpu.Feature,
        ScalarNotEqualV1BlockGpu.Identity => ScalarNotEqualV1BlockGpu.Feature,
        ScalarPositivePartV1BlockGpu.Identity => ScalarPositivePartV1BlockGpu.Feature,
        ScalarPowerV1BlockGpu.Identity => ScalarPowerV1BlockGpu.Feature,
        ScalarReciprocalV1BlockGpu.Identity => ScalarReciprocalV1BlockGpu.Feature,
        ScalarRoundV1BlockGpu.Identity => ScalarRoundV1BlockGpu.Feature,
        ScalarSelectV1BlockGpu.Identity => ScalarSelectV1BlockGpu.Feature,
        ScalarSignV1BlockGpu.Identity => ScalarSignV1BlockGpu.Feature,
        ScalarSineV1BlockGpu.Identity => ScalarSineV1BlockGpu.Feature,
        ScalarSoftplusV1BlockGpu.Identity => ScalarSoftplusV1BlockGpu.Feature,
        ScalarSquareRootV1BlockGpu.Identity => ScalarSquareRootV1BlockGpu.Feature,
        ScalarSquareV1BlockGpu.Identity => ScalarSquareV1BlockGpu.Feature,
        ScalarSubtractV1BlockGpu.Identity => ScalarSubtractV1BlockGpu.Feature,
        ScalarTangentV1BlockGpu.Identity => ScalarTangentV1BlockGpu.Feature,
        ScalarTruncateV1BlockGpu.Identity => ScalarTruncateV1BlockGpu.Feature,
        SequenceConvolutionV1BlockGpu.Identity => SequenceConvolutionV1BlockGpu.Feature,
        SequenceDifferenceV1BlockGpu.Identity => SequenceDifferenceV1BlockGpu.Feature,
        SequenceExponentialMovingAverageV1BlockGpu.Identity => SequenceExponentialMovingAverageV1BlockGpu.Feature,
        SequenceRollingMaximumV1BlockGpu.Identity => SequenceRollingMaximumV1BlockGpu.Feature,
        SequenceRollingMeanV1BlockGpu.Identity => SequenceRollingMeanV1BlockGpu.Feature,
        SequenceRollingMedianV1BlockGpu.Identity => SequenceRollingMedianV1BlockGpu.Feature,
        SequenceRollingMinimumV1BlockGpu.Identity => SequenceRollingMinimumV1BlockGpu.Feature,
        SequenceRollingQuantileV1BlockGpu.Identity => SequenceRollingQuantileV1BlockGpu.Feature,
        SequenceRollingStandardDeviationV1BlockGpu.Identity => SequenceRollingStandardDeviationV1BlockGpu.Feature,
        SequenceRollingSumV1BlockGpu.Identity => SequenceRollingSumV1BlockGpu.Feature,
        SequenceRollingVarianceV1BlockGpu.Identity => SequenceRollingVarianceV1BlockGpu.Feature,
        ShapeGreatestConvexMinorantV1BlockGpu.Identity => ShapeGreatestConvexMinorantV1BlockGpu.Feature,
        ShapeIsCompletelyMonotoneV1BlockGpu.Identity => ShapeIsCompletelyMonotoneV1BlockGpu.Feature,
        ShapeIsLogConcaveV1BlockGpu.Identity => ShapeIsLogConcaveV1BlockGpu.Feature,
        ShapeLeastConcaveMajorantV1BlockGpu.Identity => ShapeLeastConcaveMajorantV1BlockGpu.Feature,
        SpecialBetaV1BlockGpu.Identity => SpecialBetaV1BlockGpu.Feature,
        SpecialErrorFunctionV1BlockGpu.Identity => SpecialErrorFunctionV1BlockGpu.Feature,
        SpecialLogGammaV1BlockGpu.Identity => SpecialLogGammaV1BlockGpu.Feature,
        SpecialRegularizedIncompleteBetaV1BlockGpu.Identity => SpecialRegularizedIncompleteBetaV1BlockGpu.Feature,
        StateTransitionCountsV1BlockGpu.Identity => StateTransitionCountsV1BlockGpu.Feature,
        StatisticsAutocorrelationV1BlockGpu.Identity => StatisticsAutocorrelationV1BlockGpu.Feature,
        StatisticsCentralMomentV1BlockGpu.Identity => StatisticsCentralMomentV1BlockGpu.Feature,
        StatisticsCovarianceMatrixV1BlockGpu.Identity => StatisticsCovarianceMatrixV1BlockGpu.Feature,
        StatisticsDistanceCorrelationV1BlockGpu.Identity => StatisticsDistanceCorrelationV1BlockGpu.Feature,
        StatisticsHistogramV1BlockGpu.Identity => StatisticsHistogramV1BlockGpu.Feature,
        StatisticsInterquartileRangeV1BlockGpu.Identity => StatisticsInterquartileRangeV1BlockGpu.Feature,
        StatisticsKendallTauBV1BlockGpu.Identity => StatisticsKendallTauBV1BlockGpu.Feature,
        StatisticsLinearInterceptV1BlockGpu.Identity => StatisticsLinearInterceptV1BlockGpu.Feature,
        StatisticsLinearRSquaredV1BlockGpu.Identity => StatisticsLinearRSquaredV1BlockGpu.Feature,
        StatisticsLinearSlopeV1BlockGpu.Identity => StatisticsLinearSlopeV1BlockGpu.Feature,
        StatisticsMedianAbsoluteDeviationV1BlockGpu.Identity => StatisticsMedianAbsoluteDeviationV1BlockGpu.Feature,
        StatisticsPearsonCorrelationV1BlockGpu.Identity => StatisticsPearsonCorrelationV1BlockGpu.Feature,
        StatisticsPopulationCovarianceV1BlockGpu.Identity => StatisticsPopulationCovarianceV1BlockGpu.Feature,
        StatisticsPopulationExcessKurtosisV1BlockGpu.Identity => StatisticsPopulationExcessKurtosisV1BlockGpu.Feature,
        StatisticsPopulationSkewnessV1BlockGpu.Identity => StatisticsPopulationSkewnessV1BlockGpu.Feature,
        StatisticsPopulationStandardDeviationV1BlockGpu.Identity => StatisticsPopulationStandardDeviationV1BlockGpu.Feature,
        StatisticsPopulationVarianceV1BlockGpu.Identity => StatisticsPopulationVarianceV1BlockGpu.Feature,
        StatisticsPseudomedianV1BlockGpu.Identity => StatisticsPseudomedianV1BlockGpu.Feature,
        StatisticsRawMomentV1BlockGpu.Identity => StatisticsRawMomentV1BlockGpu.Feature,
        StatisticsRootMeanSquareV1BlockGpu.Identity => StatisticsRootMeanSquareV1BlockGpu.Feature,
        StatisticsSampleCovarianceV1BlockGpu.Identity => StatisticsSampleCovarianceV1BlockGpu.Feature,
        StatisticsSampleStandardDeviationV1BlockGpu.Identity => StatisticsSampleStandardDeviationV1BlockGpu.Feature,
        StatisticsSampleVarianceV1BlockGpu.Identity => StatisticsSampleVarianceV1BlockGpu.Feature,
        StatisticsSpearmanCorrelationV1BlockGpu.Identity => StatisticsSpearmanCorrelationV1BlockGpu.Feature,
        StatisticsTheilSenSlopeV1BlockGpu.Identity => StatisticsTheilSenSlopeV1BlockGpu.Feature,
        StatisticsWeightedMeanV1BlockGpu.Identity => StatisticsWeightedMeanV1BlockGpu.Feature,
        StatisticsWeightedPopulationVarianceV1BlockGpu.Identity => StatisticsWeightedPopulationVarianceV1BlockGpu.Feature,
        SurvivalDiscreteHazardV1BlockGpu.Identity => SurvivalDiscreteHazardV1BlockGpu.Feature,
        SurvivalProductLimitV1BlockGpu.Identity => SurvivalProductLimitV1BlockGpu.Feature,
        TopologyZeroDimensionalPersistenceV1BlockGpu.Identity => TopologyZeroDimensionalPersistenceV1BlockGpu.Feature,
        TransformDiscreteFourierV1BlockGpu.Identity => TransformDiscreteFourierV1BlockGpu.Feature,
        TransformHaarV1BlockGpu.Identity => TransformHaarV1BlockGpu.Feature,
        TransformInverseDiscreteFourierV1BlockGpu.Identity => TransformInverseDiscreteFourierV1BlockGpu.Feature,
        TransformWalshHadamardV1BlockGpu.Identity => TransformWalshHadamardV1BlockGpu.Feature,
        TransportAssignmentCostV1BlockGpu.Identity => TransportAssignmentCostV1BlockGpu.Feature,
        TransportCouplingCostV1BlockGpu.Identity => TransportCouplingCostV1BlockGpu.Feature,
        TransportEnergyDistanceV1BlockGpu.Identity => TransportEnergyDistanceV1BlockGpu.Feature,
        TransportMinimumAssignmentV1BlockGpu.Identity => TransportMinimumAssignmentV1BlockGpu.Feature,
        TransportMonotoneCouplingV1BlockGpu.Identity => TransportMonotoneCouplingV1BlockGpu.Feature,
        TransportOrderedEarthMoverV1BlockGpu.Identity => TransportOrderedEarthMoverV1BlockGpu.Feature,
        TransportSinkhornCouplingV1BlockGpu.Identity => TransportSinkhornCouplingV1BlockGpu.Feature,
        TransportUniformWassersteinV1BlockGpu.Identity => TransportUniformWassersteinV1BlockGpu.Feature,
        TransportWeightedWasserstein1V1BlockGpu.Identity => TransportWeightedWasserstein1V1BlockGpu.Feature,
        TropicalMaxPlusMultiplyV1BlockGpu.Identity => TropicalMaxPlusMultiplyV1BlockGpu.Feature,
        TropicalMinPlusMultiplyV1BlockGpu.Identity => TropicalMinPlusMultiplyV1BlockGpu.Feature,
        VectorAbsoluteV1BlockGpu.Identity => VectorAbsoluteV1BlockGpu.Feature,
        VectorAddScalarV1BlockGpu.Identity => VectorAddScalarV1BlockGpu.Feature,
        VectorAddV1BlockGpu.Identity => VectorAddV1BlockGpu.Feature,
        VectorAppendV1BlockGpu.Identity => VectorAppendV1BlockGpu.Feature,
        VectorArgMaximumV1BlockGpu.Identity => VectorArgMaximumV1BlockGpu.Feature,
        VectorArgMinimumV1BlockGpu.Identity => VectorArgMinimumV1BlockGpu.Feature,
        VectorConcatenateV1BlockGpu.Identity => VectorConcatenateV1BlockGpu.Feature,
        VectorCumulativeProductV1BlockGpu.Identity => VectorCumulativeProductV1BlockGpu.Feature,
        VectorCumulativeSumV1BlockGpu.Identity => VectorCumulativeSumV1BlockGpu.Feature,
        VectorDivideV1BlockGpu.Identity => VectorDivideV1BlockGpu.Feature,
        VectorDotV1BlockGpu.Identity => VectorDotV1BlockGpu.Feature,
        VectorEqualV1BlockGpu.Identity => VectorEqualV1BlockGpu.Feature,
        VectorExponentialV1BlockGpu.Identity => VectorExponentialV1BlockGpu.Feature,
        VectorGatherV1BlockGpu.Identity => VectorGatherV1BlockGpu.Feature,
        VectorGeometricMeanV1BlockGpu.Identity => VectorGeometricMeanV1BlockGpu.Feature,
        VectorGreaterThanV1BlockGpu.Identity => VectorGreaterThanV1BlockGpu.Feature,
        VectorIndexV1BlockGpu.Identity => VectorIndexV1BlockGpu.Feature,
        VectorL1NormV1BlockGpu.Identity => VectorL1NormV1BlockGpu.Feature,
        VectorL2NormV1BlockGpu.Identity => VectorL2NormV1BlockGpu.Feature,
        VectorLengthV1BlockGpu.Identity => VectorLengthV1BlockGpu.Feature,
        VectorLessThanV1BlockGpu.Identity => VectorLessThanV1BlockGpu.Feature,
        VectorLinspaceV1BlockGpu.Identity => VectorLinspaceV1BlockGpu.Feature,
        VectorMaximumV1BlockGpu.Identity => VectorMaximumV1BlockGpu.Feature,
        VectorMeanV1BlockGpu.Identity => VectorMeanV1BlockGpu.Feature,
        VectorMedianV1BlockGpu.Identity => VectorMedianV1BlockGpu.Feature,
        VectorMinimumV1BlockGpu.Identity => VectorMinimumV1BlockGpu.Feature,
        VectorMultiplyV1BlockGpu.Identity => VectorMultiplyV1BlockGpu.Feature,
        VectorNaturalLogarithmV1BlockGpu.Identity => VectorNaturalLogarithmV1BlockGpu.Feature,
        VectorNormalizeL1V1BlockGpu.Identity => VectorNormalizeL1V1BlockGpu.Feature,
        VectorNormalizeL2V1BlockGpu.Identity => VectorNormalizeL2V1BlockGpu.Feature,
        VectorPairV1BlockGpu.Identity => VectorPairV1BlockGpu.Feature,
        VectorPositivePartV1BlockGpu.Identity => VectorPositivePartV1BlockGpu.Feature,
        VectorPowerV1BlockGpu.Identity => VectorPowerV1BlockGpu.Feature,
        VectorPrependV1BlockGpu.Identity => VectorPrependV1BlockGpu.Feature,
        VectorProductV1BlockGpu.Identity => VectorProductV1BlockGpu.Feature,
        VectorQuantileV1BlockGpu.Identity => VectorQuantileV1BlockGpu.Feature,
        VectorRankV1BlockGpu.Identity => VectorRankV1BlockGpu.Feature,
        VectorRepeatV1BlockGpu.Identity => VectorRepeatV1BlockGpu.Feature,
        VectorReverseV1BlockGpu.Identity => VectorReverseV1BlockGpu.Feature,
        VectorScaleV1BlockGpu.Identity => VectorScaleV1BlockGpu.Feature,
        VectorSelectV1BlockGpu.Identity => VectorSelectV1BlockGpu.Feature,
        VectorSignV1BlockGpu.Identity => VectorSignV1BlockGpu.Feature,
        VectorSliceV1BlockGpu.Identity => VectorSliceV1BlockGpu.Feature,
        VectorSortV1BlockGpu.Identity => VectorSortV1BlockGpu.Feature,
        VectorSquareRootV1BlockGpu.Identity => VectorSquareRootV1BlockGpu.Feature,
        VectorSquareV1BlockGpu.Identity => VectorSquareV1BlockGpu.Feature,
        VectorStandardizeV1BlockGpu.Identity => VectorStandardizeV1BlockGpu.Feature,
        VectorSubtractV1BlockGpu.Identity => VectorSubtractV1BlockGpu.Feature,
        VectorSumV1BlockGpu.Identity => VectorSumV1BlockGpu.Feature,
        VectorUniqueV1BlockGpu.Identity => VectorUniqueV1BlockGpu.Feature,
        _ => throw new NotSupportedException($"MathBlock '{identity}' has no GPU implementation.")
    };
}
